




import { useState, useMemo, useCallback } from 'react';
import {
  AlertTriangle, Shield, Link2, ArrowRight, ArrowLeftRight, ChevronRight, ChevronDown, ChevronUp,
  Search, Filter, Plus, RefreshCw, CheckCircle2, XCircle, Clock, AlertCircle, Target, Activity,
  TrendingUp, TrendingDown, Minus, Zap, FileText, GitBranch, Network, Eye, Edit3, Sparkles,
  ArrowUpRight, ArrowDownRight, BarChart3, Layers, CircleDot, History, Users, Calendar, Play, Settings,
  Rocket, Bell
} from 'lucide-react';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { CapabilityGate } from '@/components/ui/CapabilityGate';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import { SearchInput } from '@/components/ui/Input';
import { ProgressBar } from '@/components/ui/Progress';
import { useQMSStore } from '@/store/useQMSStore';
import { useCrossModuleEventStore } from '@/store/useCrossModuleEventStore';
import { useToast, useToastStore } from '@/components/ui/Toast';
import type { BadgeColor } from '@/components/ui/Badge';
import { useDeadClick } from '@/hooks/useDeadClick';

// =============================================================================
// TYPES
// =============================================================================

export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type RiskStatus = 'identified' | 'analyzing' | 'mitigating' | 'monitoring' | 'closed' | 'accepted';
export type CAPAStatus = 'draft' | 'pending-approval' | 'approved' | 'investigation' | 'action-planning' | 'implementation' | 'effectiveness-check' | 'closed' | 'closed-ineffective' | 'cancelled';
export type LinkType = 'risk-triggered-capa' | 'capa-mitigates-risk' | 'effectiveness-updates-risk' | 'manual-link';
export type IntegrationEventType = 'capa-created-from-risk' | 'risk-updated-from-capa' | 'effectiveness-propagated' | 'link-established' | 'auto-generation-triggered';
export type AutoGenerationRule = 'high-risk-auto-capa' | 'critical-risk-immediate' | 'threshold-breach' | 'manual-only';
export type EffectivenessResult = 'effective' | 'partially-effective' | 'ineffective' | 'pending';

export interface Risk {
  id: string;
  riskNumber: string;
  title: string;
  description: string;
  category: string;
  riskLevel: RiskLevel;
  status: RiskStatus;
  owner: string;
  department: string;
  probability: number;
  impact: number;
  riskScore: number;
  residualRiskLevel?: RiskLevel;
  mitigationPlan?: string;
  linkedCAPAs: string[];
  createdAt: string;
  updatedAt: string;
}

export interface RiskCAPALink {
  id: string;
  riskId: string;
  riskNumber: string;
  riskTitle: string;
  riskLevel: RiskLevel;
  capaId: string;
  capaNumber: string;
  capaTitle: string;
  capaStatus: CAPAStatus;
  linkType: LinkType;
  linkDirection: 'risk-to-capa' | 'capa-to-risk' | 'bidirectional';
  autoGenerated: boolean;
  triggeredRule?: AutoGenerationRule;
  effectivenessImpact?: {
    result: EffectivenessResult;
    riskReduction: number;
    updatedResidualLevel?: RiskLevel;
  };
  notes?: string;
  createdAt: string;
  createdBy: string;
}

export interface IntegrationEvent {
  id: string;
  eventType: IntegrationEventType;
  sourceType: 'risk' | 'capa';
  sourceId: string;
  sourceNumber: string;
  targetType: 'risk' | 'capa';
  targetId: string;
  targetNumber: string;
  description: string;
  automated: boolean;
  timestamp: string;
  performedBy: string;
  metadata?: Record<string, unknown>;
}

export interface AutoGenerationConfig {
  id: string;
  rule: AutoGenerationRule;
  enabled: boolean;
  triggerConditions: {
    riskLevelThreshold: RiskLevel;
    categories: string[];
    requiresApproval: boolean;
  };
  capaTemplate: {
    capaType: 'corrective' | 'preventive' | 'both';
    priority: 'low' | 'medium' | 'high' | 'critical';
    defaultTargetDays: number;
    assignToRiskOwner: boolean;
  };
  lastTriggered?: string;
  triggerCount: number;
}

// =============================================================================
// MOCK DATA - Enhanced with actionable risks
// =============================================================================

const mockRisks: Risk[] = [
  {
    id: 'risk-001', riskNumber: 'RSK-2026-0001', title: 'API Particle Size Variability',
    description: 'Inconsistent particle size distribution affecting dissolution profile',
    category: 'manufacturing', riskLevel: 'high', status: 'mitigating',
    owner: 'Dr. Sarah Chen', department: 'CMC', probability: 4, impact: 4, riskScore: 16,
    linkedCAPAs: [], createdAt: '2026-01-10T08:00:00Z', updatedAt: '2026-01-15T10:30:00Z'
  },
  {
    id: 'risk-002', riskNumber: 'RSK-2026-0002', title: 'Hepatotoxicity Signal Detection',
    description: 'Emerging liver enzyme elevation pattern in Phase 3 trial',
    category: 'clinical-safety', riskLevel: 'critical', status: 'analyzing',
    owner: 'Dr. Michael Torres', department: 'Safety', probability: 3, impact: 5, riskScore: 15,
    linkedCAPAs: [], createdAt: '2026-01-12T14:00:00Z', updatedAt: '2026-01-18T09:15:00Z'
  },
  {
    id: 'risk-003', riskNumber: 'RSK-2026-0003', title: 'Supply Chain Single Source Risk',
    description: 'Critical excipient with single qualified supplier',
    category: 'supply-chain', riskLevel: 'high', status: 'identified',
    owner: 'Jennifer Walsh', department: 'Supply Chain', probability: 3, impact: 4, riskScore: 12,
    linkedCAPAs: [], createdAt: '2026-01-05T11:00:00Z', updatedAt: '2026-01-14T16:45:00Z'
  },
  {
    id: 'risk-004', riskNumber: 'RSK-2026-0004', title: 'Stability Data Trending Concern',
    description: 'Assay trending toward specification limit at 24-month timepoint',
    category: 'quality', riskLevel: 'medium', status: 'monitoring',
    owner: 'Dr. Robert Kim', department: 'QC', probability: 2, impact: 3, riskScore: 6,
    linkedCAPAs: [], createdAt: '2026-01-08T09:30:00Z', updatedAt: '2026-01-17T14:20:00Z'
  },
  {
    id: 'risk-005', riskNumber: 'RSK-2026-0005', title: 'Data Integrity Gap in Lab Systems',
    description: 'Audit trail gaps identified in legacy LIMS integration',
    category: 'compliance', riskLevel: 'critical', status: 'identified',
    owner: 'Amanda Foster', department: 'Quality', probability: 4, impact: 5, riskScore: 20,
    linkedCAPAs: [], createdAt: '2026-01-15T08:00:00Z', updatedAt: '2026-01-18T11:00:00Z'
  }
];

const mockAutoGenerationConfigs: AutoGenerationConfig[] = [
  {
    id: 'config-001', rule: 'critical-risk-immediate', enabled: true,
    triggerConditions: { riskLevelThreshold: 'critical', categories: ['clinical-safety', 'compliance', 'manufacturing'], requiresApproval: false },
    capaTemplate: { capaType: 'both', priority: 'critical', defaultTargetDays: 14, assignToRiskOwner: true },
    lastTriggered: '2026-01-15T10:00:00Z', triggerCount: 3
  },
  {
    id: 'config-002', rule: 'high-risk-auto-capa', enabled: true,
    triggerConditions: { riskLevelThreshold: 'high', categories: ['manufacturing', 'quality', 'supply-chain'], requiresApproval: true },
    capaTemplate: { capaType: 'corrective', priority: 'high', defaultTargetDays: 30, assignToRiskOwner: true },
    lastTriggered: '2026-01-12T14:30:00Z', triggerCount: 7
  },
  {
    id: 'config-003', rule: 'threshold-breach', enabled: false,
    triggerConditions: { riskLevelThreshold: 'medium', categories: ['quality'], requiresApproval: true },
    capaTemplate: { capaType: 'preventive', priority: 'medium', defaultTargetDays: 60, assignToRiskOwner: false },
    triggerCount: 0
  }
];

// =============================================================================
// BADGE HELPERS
// =============================================================================

const getRiskLevelBadge = (level: RiskLevel, size: 'xs' | 'sm' = 'sm') => {
  const config: Record<RiskLevel, { color: BadgeColor; label: string }> = {
    low: { color: 'emerald', label: 'Low' },
    medium: { color: 'amber', label: 'Medium' },
    high: { color: 'orange', label: 'High' },
    critical: { color: 'red', label: 'Critical' }
  };
  return <Badge color={config[level].color} size={size}>{config[level].label}</Badge>;
};

const getRiskStatusBadge = (status: RiskStatus, size: 'xs' | 'sm' = 'sm') => {
  const config: Record<RiskStatus, { color: BadgeColor; label: string }> = {
    identified: { color: 'blue', label: 'Identified' },
    analyzing: { color: 'purple', label: 'Analyzing' },
    mitigating: { color: 'amber', label: 'Mitigating' },
    monitoring: { color: 'cyan', label: 'Monitoring' },
    closed: { color: 'emerald', label: 'Closed' },
    accepted: { color: 'slate', label: 'Accepted' }
  };
  return <Badge color={config[status].color} size={size}>{config[status].label}</Badge>;
};

const getCAPAStatusBadge = (status: CAPAStatus, size: 'xs' | 'sm' = 'sm') => {
  const config: Record<CAPAStatus, { color: BadgeColor; label: string }> = {
    draft: { color: 'slate', label: 'Draft' },
    'pending-approval': { color: 'amber', label: 'Pending Approval' },
    approved: { color: 'blue', label: 'Approved' },
    investigation: { color: 'purple', label: 'Investigation' },
    'action-planning': { color: 'cyan', label: 'Action Planning' },
    implementation: { color: 'orange', label: 'Implementation' },
    'effectiveness-check': { color: 'pink', label: 'Effectiveness Check' },
    closed: { color: 'emerald', label: 'Closed' },
    'closed-ineffective': { color: 'red', label: 'Closed - Ineffective' },
    cancelled: { color: 'slate', label: 'Cancelled' }
  };
  return <Badge color={config[status]?.color || 'slate'} size={size}>{config[status]?.label || status}</Badge>;
};

const getLinkTypeBadge = (linkType: LinkType) => {
  const config: Record<LinkType, { color: BadgeColor; label: string }> = {
    'risk-triggered-capa': { color: 'blue', label: 'Risk → CAPA' },
    'capa-mitigates-risk': { color: 'emerald', label: 'CAPA → Risk' },
    'effectiveness-updates-risk': { color: 'purple', label: 'Effectiveness' },
    'manual-link': { color: 'slate', label: 'Manual Link' }
  };
  return <Badge color={config[linkType].color} size="xs">{config[linkType].label}</Badge>;
};

const getEventTypeBadge = (eventType: IntegrationEventType) => {
  const config: Record<IntegrationEventType, { color: BadgeColor; label: string }> = {
    'capa-created-from-risk': { color: 'blue', label: 'CAPA Created' },
    'risk-updated-from-capa': { color: 'emerald', label: 'Risk Updated' },
    'effectiveness-propagated': { color: 'purple', label: 'Effectiveness' },
    'link-established': { color: 'cyan', label: 'Link Created' },
    'auto-generation-triggered': { color: 'amber', label: 'Auto-Generated' }
  };
  return <Badge color={config[eventType].color} size="xs">{config[eventType].label}</Badge>;
};

// =============================================================================
// MAIN COMPONENT
// =============================================================================

export function RiskCAPAIntegrationDashboard() {
  // Local state
    const { deadClick } = useDeadClick();
  const [activeView, setActiveView] = useState<'risks' | 'links' | 'events' | 'config'>('risks');
  const [searchQuery, setSearchQuery] = useState('');
  const [filterRiskLevel, setFilterRiskLevel] = useState<RiskLevel | 'all'>('all');
  const [filterEventType, setFilterEventType] = useState<IntegrationEventType | 'all'>('all');
  const [selectedRiskId, setSelectedRiskId] = useState<string | null>(null);
  const [selectedLinkId, setSelectedLinkId] = useState<string | null>(null);
  const [selectedConfigId, setSelectedConfigId] = useState<string | null>(null);
  const [isCreatingCAPA, setIsCreatingCAPA] = useState(false);
  const [showCascadeFlow, setShowCascadeDemo] = useState(false);
  
  // Internal state for risks and links
  const [risks, setRisks] = useState<Risk[]>(mockRisks);
  const [links, setLinks] = useState<RiskCAPALink[]>([]);
  const [events, setEvents] = useState<IntegrationEvent[]>([]);
  const [configs] = useState<AutoGenerationConfig[]>(mockAutoGenerationConfigs);
  
  // External stores
  const { createCAPA, capas } = useQMSStore();
  const { emitEvent } = useCrossModuleEventStore();
  const toast = useToast();
  const addToast = useToastStore((s) => s.addToast);

  // Selected items
  const selectedRisk = useMemo(() => risks.find(r => r.id === selectedRiskId), [risks, selectedRiskId]);
  const selectedLink = useMemo(() => links.find(l => l.id === selectedLinkId), [links, selectedLinkId]);
  const selectedConfig = useMemo(() => configs.find(c => c.id === selectedConfigId), [configs, selectedConfigId]);

  // Stats
  const stats = useMemo(() => ({
    totalRisks: risks.length,
    criticalRisks: risks.filter(r => r.riskLevel === 'critical').length,
    highRisks: risks.filter(r => r.riskLevel === 'high').length,
    activeLinks: links.length,
    autoGeneratedCAPAs: links.filter(l => l.autoGenerated).length,
    pendingActions: risks.filter(r => r.status === 'identified' && (r.riskLevel === 'critical' || r.riskLevel === 'high')).length
  }), [risks, links]);

  // Filter risks
  const filteredRisks = useMemo(() => {
    return risks.filter(r => {
      const matchesSearch = !searchQuery || 
        r.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        r.riskNumber.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesLevel = filterRiskLevel === 'all' || r.riskLevel === filterRiskLevel;
      return matchesSearch && matchesLevel;
    });
  }, [risks, searchQuery, filterRiskLevel]);

  // Filter events
  const filteredEvents = useMemo(() => {
    return events.filter(e => {
      const matchesSearch = !searchQuery || e.description.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesType = filterEventType === 'all' || e.eventType === filterEventType;
      return matchesSearch && matchesType;
    });
  }, [events, searchQuery, filterEventType]);

  // ==========================================================================
  // BUSINESS LOGIC - Create CAPA from Risk
  // ==========================================================================

  const createCAPAFromRisk = useCallback(async (risk: Risk, autoGenerated: boolean = false) => {
    setIsCreatingCAPA(true);
    
    try {
      // Simulate processing time for demo
      await new Promise(resolve => setTimeout(resolve, 800));

      // Find matching auto-gen config
      const matchingConfig = configs.find(c => 
        c.enabled && 
        (c.triggerConditions.riskLevelThreshold === risk.riskLevel ||
         (c.triggerConditions.riskLevelThreshold === 'high' && risk.riskLevel === 'critical'))
      );

      // Create CAPA in QMS store
      const capaData = {
        title: `CAPA from Risk: ${risk.title}`,
        description: `Corrective/Preventive Action initiated from risk assessment.\n\nSource Risk: ${risk.riskNumber}\nRisk Level: ${risk.riskLevel.toUpperCase()}\n\n${risk.description}`,
        capaType: matchingConfig?.capaTemplate.capaType || 'corrective',
        source: 'risk-assessment' as const,
        sourceRecordId: risk.id,
        sourceRecordNumber: risk.riskNumber,
        priority: matchingConfig?.capaTemplate.priority || (risk.riskLevel === 'critical' ? 'critical' : 'high'),
        severity: risk.riskLevel === 'critical' ? 'critical' as const : risk.riskLevel === 'high' ? 'major' as const : 'minor' as const,
        department: (risk.department.toLowerCase().replace(' ', '-') as 'quality-assurance'),
        assigneeName: matchingConfig?.capaTemplate.assignToRiskOwner ? risk.owner : '',
        ownerName: risk.owner,
        regulatoryImpact: risk.category === 'compliance' || risk.category === 'clinical-safety',
        targetCompletionDate: new Date(Date.now() + (matchingConfig?.capaTemplate.defaultTargetDays || 30) * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
      };

      const newCAPA = createCAPA(capaData);
      const capaNumber = newCAPA.capaNumber;

      // Create link record
      const newLink: RiskCAPALink = {
        id: `link-${Date.now()}`,
        riskId: risk.id,
        riskNumber: risk.riskNumber,
        riskTitle: risk.title,
        riskLevel: risk.riskLevel,
        capaId: newCAPA.id,
        capaNumber: capaNumber,
        capaTitle: newCAPA.title,
        capaStatus: 'draft',
        linkType: 'risk-triggered-capa',
        linkDirection: 'risk-to-capa',
        autoGenerated,
        triggeredRule: matchingConfig?.rule,
        createdAt: new Date().toISOString(),
        createdBy: autoGenerated ? 'System (Auto-Generation)' : 'Current User'
      };
      setLinks(prev => [newLink, ...prev]);

      // Create integration event
      const newEvent: IntegrationEvent = {
        id: `event-${Date.now()}`,
        eventType: autoGenerated ? 'auto-generation-triggered' : 'capa-created-from-risk',
        sourceType: 'risk',
        sourceId: risk.id,
        sourceNumber: risk.riskNumber,
        targetType: 'capa',
        targetId: newCAPA.id,
        targetNumber: capaNumber,
        description: `${autoGenerated ? 'Auto-generated' : 'Created'} ${capaNumber} from ${risk.riskLevel} risk ${risk.riskNumber}: "${risk.title}"`,
        automated: autoGenerated,
        timestamp: new Date().toISOString(),
        performedBy: autoGenerated ? 'System' : 'Current User',
        metadata: {
          riskLevel: risk.riskLevel,
          riskCategory: risk.category,
          capaType: capaData.capaType,
          capaPriority: capaData.priority,
          targetDays: matchingConfig?.capaTemplate.defaultTargetDays || 30
        }
      };
      setEvents(prev => [newEvent, ...prev]);

      // Update risk with linked CAPA
      setRisks(prev => prev.map(r => 
        r.id === risk.id 
          ? { ...r, linkedCAPAs: [...r.linkedCAPAs, newCAPA.id], status: 'mitigating', updatedAt: new Date().toISOString() }
          : r
      ));

      // Emit cross-module event
      emitEvent(
        'capa-created',
        'qms',
        {
          capaId: newCAPA.id,
          capaNumber,
          sourceRisk: risk.riskNumber,
          riskLevel: risk.riskLevel,
          priority: capaData.priority,
          autoGenerated
        },
        {
          correlationId: `risk-capa-${risk.id}`,
          priority: risk.riskLevel === 'critical' ? 'critical' : 'high',
          automated: true,
          requiresReview: true
        }
      );

      // Success toast
      addToast({
        title: 'CAPA Created Successfully',
        description: `${capaNumber} created from ${risk.riskNumber}. Risk status updated to "Mitigating".`,
        message: `${capaNumber} created from ${risk.riskNumber}. Risk status updated to "Mitigating".`,
        type: 'success',
        duration: 5000
      });

      return newCAPA;

    } catch (error) {
      addToast({
        title: 'CAPA Creation Failed',
        message: 'Unable to create CAPA. Please try again.',
        description: 'Unable to create CAPA. Please try again.',
        type: 'error'
      });
      throw error;
    } finally {
      setIsCreatingCAPA(false);
    }
  }, [configs, createCAPA, emitEvent, addToast]);

  // ==========================================================================
  // Cascade scenario (shows full risk-to-CAPA flow)
  // ==========================================================================

  const runCascadeFlow = useCallback(async () => {
    setShowCascadeDemo(true);
    
    // Find a critical risk without linked CAPA
    const demoRisk = risks.find(r => r.riskLevel === 'critical' && r.linkedCAPAs.length === 0);
    
    if (!demoRisk) {
      addToast({
        title: 'No Unlinked Risks',
        message: 'All critical risks already have linked CAPAs.',
        description: 'All critical risks already have linked CAPAs.',
        type: 'info'
      });
      setShowCascadeDemo(false);
      return;
    }

    // Step 1: Highlight the risk
    setActiveView('risks');
    setSelectedRiskId(demoRisk.id);
    addToast({
      title: '🔍 Step 1: Risk Identified',
      message: `Critical risk detected: ${demoRisk.riskNumber}`,
      description: `Critical risk detected: ${demoRisk.riskNumber}`,
      type: 'info',
      duration: 2500
    });

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Step 2: Auto-generate CAPA
    addToast({
      title: '⚡ Step 2: Auto-Generation Triggered',
      message: 'Critical risk rule matched - initiating CAPA creation...',
      description: 'Critical risk rule matched - initiating CAPA creation...',
      type: 'info',
      duration: 2500
    });

    await new Promise(resolve => setTimeout(resolve, 1500));

    // Create the CAPA
    const newCAPA = await createCAPAFromRisk(demoRisk, true);

    await new Promise(resolve => setTimeout(resolve, 1500));

    // Step 3: Show the link
    setActiveView('links');
    addToast({
      title: '🔗 Step 3: Link Established',
      message: `${demoRisk.riskNumber} → ${newCAPA.capaNumber}`,
      description: `${demoRisk.riskNumber} → ${newCAPA.capaNumber}`,
      type: 'success',
      duration: 2500
    });

    await new Promise(resolve => setTimeout(resolve, 2000));

    // Step 4: Show cross-module notification
    addToast({
      title: '📣 Step 4: Cross-Module Notification',
      message: 'QMS, Safety, and Regulatory teams notified of new CAPA',
      description: 'QMS, Safety, and Regulatory teams notified of new CAPA',
      type: 'success',
      duration: 3000
    });

    setShowCascadeDemo(false);
  }, [risks, createCAPAFromRisk, addToast]);

  return (
    <div className="h-full flex flex-col bg-surface">
      <ScreenHeader
        moduleId="qms"
        title="Risk-CAPA Integration"
        subtitle="Automated risk mitigation workflow with bidirectional traceability"
        icon={<GitBranch className="w-5 h-5" />}
        actions={
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" icon={<Rocket className="w-4 h-4" />} onClick={runCascadeFlow} disabled={showCascadeFlow}>
              {showCascadeFlow ? 'Running...' : 'Run Cascade Scenario'}
            </Button>
            <CapabilityGate moduleId="qms" capability="author" inline>
              <Button variant="primary" size="sm" icon={<Plus className="w-4 h-4" onClick={() => toast.success('CAPA action recorded — assigned owner notified')} />}>
                Link Risk to CAPA
              </Button>
            </CapabilityGate>
          </div>
        }
      >
        {/* STATS ROW */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 lg:gap-4">
          <div className="bg-surface-card border border-border rounded-lg p-4">
            <div className="text-2xl font-bold text-text-primary">{stats.totalRisks}</div>
            <div className="text-xs text-text-muted">Total Risks</div>
          </div>
          <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-red-400">{stats.criticalRisks}</div>
            <div className="text-xs text-red-400/80">Critical</div>
          </div>
          <div className="bg-orange-500/10 border border-orange-500/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-orange-400">{stats.highRisks}</div>
            <div className="text-xs text-orange-400/80">High</div>
          </div>
          <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-purple-400">{stats.activeLinks}</div>
            <div className="text-xs text-purple-400/80">Active Links</div>
          </div>
          <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-blue-400">{stats.autoGeneratedCAPAs}</div>
            <div className="text-xs text-blue-400/80">Auto-Generated</div>
          </div>
          <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-amber-400">{stats.pendingActions}</div>
            <div className="text-xs text-amber-400/80">Pending Action</div>
          </div>
        </div>

        {/* VIEW TABS */}
        <div className="flex gap-1 mt-4 bg-surface-card p-1 rounded-lg w-fit">
          {(['risks', 'links', 'events', 'config'] as const).map(view => (
            <button
              key={view}
              onClick={() => setActiveView(view)}
              className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${
                activeView === view
                  ? 'bg-accent-blue text-white'
                  : 'text-text-secondary hover:text-text-primary hover:bg-surface-elevated'
              }`}
            >
              {view === 'risks' && <><AlertTriangle className="w-4 h-4 inline-block mr-1" />Risks</>}
              {view === 'links' && <><Link2 className="w-4 h-4 inline-block mr-1" />Links</>}
              {view === 'events' && <><History className="w-4 h-4 inline-block mr-1" />Events</>}
              {view === 'config' && <><Settings className="w-4 h-4 inline-block mr-1" />Config</>}
            </button>
          ))}
        </div>
            </ScreenHeader>


      {/* CONTENT */}
      <div className="flex-1 overflow-auto p-6">
        {/* RISKS VIEW */}
        {activeView === 'risks' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6">
            <div className="col-span-1 md:col-span-2 space-y-4">
              <div className="flex items-center gap-4">
                <SearchInput
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search risks..."
                  className="flex-1"
                />
                <select
                  value={filterRiskLevel}
                  onChange={(e) => setFilterRiskLevel(e.target.value as RiskLevel | 'all')}
                  className="px-3 py-2 bg-surface-card border border-border rounded-lg text-sm text-text-primary"
                >
                  <option value="all">All Levels</option>
                  <option value="critical">Critical</option>
                  <option value="high">High</option>
                  <option value="medium">Medium</option>
                  <option value="low">Low</option>
                </select>
              </div>
              
              <div className="space-y-3">
                {filteredRisks.map(risk => (
                  <Card 
                    key={risk.id} 
                    className={`cursor-pointer transition-all ${
                      selectedRiskId === risk.id 
                        ? 'border-amber-500/50 bg-amber-500/5' 
                        : 'hover:border-amber-500/30'
                    }`}
                    onClick={() => setSelectedRiskId(risk.id)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-xs font-mono text-text-muted">{risk.riskNumber}</span>
                            {getRiskLevelBadge(risk.riskLevel, 'xs')}
                            {getRiskStatusBadge(risk.status, 'xs')}
                            {risk.linkedCAPAs.length > 0 && (
                              <Badge color="purple" size="xs" icon={<Link2 className="w-3 h-3" />}>
                                {risk.linkedCAPAs.length} CAPA
                              </Badge>
                            )}
                          </div>
                          <h4 className="text-sm font-medium text-text-primary">{risk.title}</h4>
                          <div className="text-xs text-text-muted mt-1">{risk.department} • Score: {risk.riskScore}</div>
                        </div>
                        <div className="flex flex-col items-end gap-2">
                          <div className="w-16 h-16 relative">
                            <svg className="w-16 h-16 transform -rotate-90">
                              <circle cx="32" cy="32" r="28" fill="none" stroke="currentColor" strokeWidth="6" className="text-surface-elevated" />
                              <circle 
                                cx="32" cy="32" r="28" fill="none" 
                                stroke={risk.riskScore >= 15 ? '#EF4444' : risk.riskScore >= 10 ? '#F97316' : risk.riskScore >= 5 ? '#F59E0B' : '#10B981'} 
                                strokeWidth="6" 
                                strokeDasharray={`${(risk.riskScore / 25) * 176} 176`}
                                strokeLinecap="round"
                              />
                            </svg>
                            <div className="absolute inset-0 flex items-center justify-center">
                              <span className="text-sm font-bold text-text-primary">{risk.riskScore}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
            
            {/* RISK DETAIL PANEL */}
            <div>
              {selectedRisk ? (
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <AlertTriangle className="w-5 h-5 text-amber-400" />
                      <h3 className="text-sm font-medium text-text-primary">Risk Details</h3>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <div className="text-xs text-text-muted mb-1">Risk Number</div>
                        <div className="text-sm font-medium text-text-primary">{selectedRisk.riskNumber}</div>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-1">Title</div>
                        <div className="text-sm text-text-primary">{selectedRisk.title}</div>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-1">Description</div>
                        <div className="text-sm text-text-secondary">{selectedRisk.description}</div>
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                        <div>
                          <div className="text-xs text-text-muted mb-1">Level</div>
                          {getRiskLevelBadge(selectedRisk.riskLevel)}
                        </div>
                        <div>
                          <div className="text-xs text-text-muted mb-1">Status</div>
                          {getRiskStatusBadge(selectedRisk.status)}
                        </div>
                      </div>
                      <div className="grid grid-cols-3 gap-2 p-3 bg-surface rounded-lg">
                        <div className="text-center">
                          <div className="text-lg font-bold text-text-primary">{selectedRisk.probability}</div>
                          <div className="text-xs text-text-muted">Probability</div>
                        </div>
                        <div className="text-center">
                          <div className="text-lg font-bold text-text-primary">{selectedRisk.impact}</div>
                          <div className="text-xs text-text-muted">Impact</div>
                        </div>
                        <div className="text-center">
                          <div className="text-lg font-bold text-amber-400">{selectedRisk.riskScore}</div>
                          <div className="text-xs text-text-muted">Score</div>
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-1">Owner</div>
                        <div className="text-sm text-text-primary">{selectedRisk.owner}</div>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-1">Department</div>
                        <div className="text-sm text-text-primary">{selectedRisk.department}</div>
                      </div>
                      
                      {/* Linked CAPAs */}
                      {selectedRisk.linkedCAPAs.length > 0 && (
                        <div>
                          <div className="text-xs text-text-muted mb-2">Linked CAPAs</div>
                          <div className="space-y-2">
                            {links.filter(l => l.riskId === selectedRisk.id).map(link => (
                              <div key={link.id} className="p-2 bg-purple-500/10 rounded-lg flex items-center justify-between">
                                <div>
                                  <div className="text-sm font-medium text-text-primary">{link.capaNumber}</div>
                                  <div className="text-xs text-text-muted">{link.capaTitle}</div>
                                </div>
                                {getCAPAStatusBadge(link.capaStatus, 'xs')}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      
                      {/* Action Buttons */}
                      <div className="pt-4 border-t border-border space-y-2">
                        {selectedRisk.linkedCAPAs.length === 0 && (
                          <Button
                            variant="primary" 
                            size="sm" 
                            className="w-full"
                            icon={<Zap className="w-4 h-4" />}
                            onClick={() => createCAPAFromRisk(selectedRisk, false)}
                            disabled={isCreatingCAPA}
                          >
                            {isCreatingCAPA ? 'Creating CAPA...' : 'Create CAPA from Risk'}
                          </Button>
                        )}
                        <Button variant="outline" size="sm" className="w-full" icon={<Edit3 className="w-4 h-4" onClick={() => toast.success('CAPA action recorded — assigned owner notified')} />}>
                          Edit Risk
                        </Button>
                        <Button variant="outline" size="sm" className="w-full" icon={<Eye className="w-4 h-4" onClick={() => toast.success('CAPA action recorded — assigned owner notified')} />}>
                          View Full Assessment
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card>
                  <CardContent className="p-8 text-center">
                    <AlertTriangle className="w-12 h-12 text-text-muted mx-auto mb-3" />
                    <div className="text-sm text-text-muted">Select a risk to view details</div>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        )}

        {/* LINKS VIEW */}
        {activeView === 'links' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6">
            <div className="col-span-1 md:col-span-2 space-y-4">
              <div className="flex items-center gap-4">
                <SearchInput
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search links..."
                  className="flex-1"
                />
              </div>
              
              {links.length === 0 ? (
                <Card>
                  <CardContent className="p-12 text-center">
                    <Link2 className="w-16 h-16 text-text-muted mx-auto mb-4" />
                    <h3 className="text-lg font-medium text-text-primary mb-2">No Links Yet</h3>
                    <p className="text-sm text-text-muted mb-4">Create a CAPA from a risk to establish the first link</p>
                    <Button 
                      variant="primary"
                      onClick={() => setActiveView('risks')}
                      icon={<ArrowRight className="w-4 h-4" />}
                    >
                      Go to Risks
                    </Button>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {links.map(link => (
                    <Card 
                      key={link.id}
                      className={`cursor-pointer transition-all ${
                        selectedLinkId === link.id 
                          ? 'border-purple-500/50 bg-purple-500/5' 
                          : 'hover:border-purple-500/30'
                      }`}
                      onClick={() => setSelectedLinkId(link.id)}
                    >
                      <CardContent className="p-4">
                        <div className="flex items-center gap-4">
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              {getRiskLevelBadge(link.riskLevel, 'xs')}
                              <span className="text-sm font-medium text-text-primary">{link.riskNumber}</span>
                            </div>
                            <div className="text-xs text-text-muted">{link.riskTitle}</div>
                          </div>
                          <div className="flex flex-col items-center px-4">
                            {link.autoGenerated && (
                              <Badge color="blue" size="xs" className="mb-1">Auto</Badge>
                            )}
                            <ArrowRight className="w-6 h-6 text-purple-400" />
                            {getLinkTypeBadge(link.linkType)}
                          </div>
                          <div className="flex-1 text-right">
                            <div className="flex items-center justify-end gap-2 mb-2">
                              <span className="text-sm font-medium text-text-primary">{link.capaNumber}</span>
                              {getCAPAStatusBadge(link.capaStatus, 'xs')}
                            </div>
                            <div className="text-xs text-text-muted">{link.capaTitle}</div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </div>
            
            {/* Link Detail */}
            <div>
              {selectedLink ? (
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <Link2 className="w-5 h-5 text-purple-400" />
                      <h3 className="text-sm font-medium text-text-primary">Link Details</h3>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div className="p-3 bg-red-500/10 rounded-lg">
                        <div className="text-xs text-text-muted mb-1">Source Risk</div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-sm font-medium text-text-primary">{selectedLink.riskNumber}</span>
                          {getRiskLevelBadge(selectedLink.riskLevel, 'xs')}
                        </div>
                        <div className="text-sm text-text-secondary">{selectedLink.riskTitle}</div>
                      </div>
                      
                      <div className="flex justify-center">
                        <ArrowRight className="w-8 h-8 text-purple-400" />
                      </div>
                      
                      <div className="p-3 bg-emerald-500/10 rounded-lg">
                        <div className="text-xs text-text-muted mb-1">Target CAPA</div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-sm font-medium text-text-primary">{selectedLink.capaNumber}</span>
                          {getCAPAStatusBadge(selectedLink.capaStatus, 'xs')}
                        </div>
                        <div className="text-sm text-text-secondary">{selectedLink.capaTitle}</div>
                      </div>
                      
                      <div>
                        <div className="text-xs text-text-muted mb-1">Link Type</div>
                        {getLinkTypeBadge(selectedLink.linkType)}
                      </div>
                      
                      <div className="pt-4 border-t border-border space-y-2">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-text-muted">Created</span>
                          <span className="text-text-secondary">{new Date(selectedLink.createdAt).toLocaleString()}</span>
                        </div>
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-text-muted">Created By</span>
                          <span className="text-text-secondary">{selectedLink.createdBy}</span>
                        </div>
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-text-muted">Auto-Generated</span>
                          <Badge color={selectedLink.autoGenerated ? 'blue' : 'slate'} size="xs">
                            {selectedLink.autoGenerated ? 'Yes' : 'No'}
                          </Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card>
                  <CardContent className="p-8 text-center">
                    <Link2 className="w-12 h-12 text-text-muted mx-auto mb-3" />
                    <div className="text-sm text-text-muted">Select a link to view details</div>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        )}

        {/* EVENTS VIEW */}
        {activeView === 'events' && (
          <div className="space-y-4">
            <div className="flex items-center gap-4">
              <SearchInput
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search events..."
                className="flex-1"
              />
              <select
                value={filterEventType}
                onChange={(e) => setFilterEventType(e.target.value as IntegrationEventType | 'all')}
                className="px-3 py-2 bg-surface-card border border-border rounded-lg text-sm text-text-primary"
              >
                <option value="all">All Event Types</option>
                <option value="capa-created-from-risk">CAPA Created from Risk</option>
                <option value="risk-updated-from-capa">Risk Updated from CAPA</option>
                <option value="effectiveness-propagated">Effectiveness Propagated</option>
                <option value="link-established">Link Established</option>
                <option value="auto-generation-triggered">Auto Generation Triggered</option>
              </select>
            </div>
            
            {events.length === 0 ? (
              <Card>
                <CardContent className="p-12 text-center">
                  <History className="w-16 h-16 text-text-muted mx-auto mb-4" />
                  <h3 className="text-lg font-medium text-text-primary mb-2">No Events Yet</h3>
                  <p className="text-sm text-text-muted">Events will appear here as you create CAPAs from risks</p>
                </CardContent>
              </Card>
            ) : (
              <div className="space-y-3">
                {filteredEvents.map(event => (
                  <Card key={event.id}>
                    <CardContent className="p-4">
                      <div className="flex items-start gap-4">
                        <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${
                          event.automated ? 'bg-blue-500/20' : 'bg-purple-500/20'
                        }`}>
                          {event.eventType === 'capa-created-from-risk' && <Plus className="w-5 h-5 text-blue-400" />}
                          {event.eventType === 'auto-generation-triggered' && <Zap className="w-5 h-5 text-amber-400" />}
                          {event.eventType === 'risk-updated-from-capa' && <RefreshCw className="w-5 h-5 text-emerald-400" />}
                          {event.eventType === 'effectiveness-propagated' && <CheckCircle2 className="w-5 h-5 text-purple-400" />}
                          {event.eventType === 'link-established' && <Link2 className="w-5 h-5 text-cyan-400" />}
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            {getEventTypeBadge(event.eventType)}
                            {event.automated && <Badge color="blue" size="xs">Automated</Badge>}
                            <span className="text-xs text-text-muted ml-auto">{new Date(event.timestamp).toLocaleString()}</span>
                          </div>
                          <div className="text-sm text-text-primary mb-2">{event.description}</div>
                          <div className="flex items-center gap-4 text-xs">
                            <div className="flex items-center gap-2">
                              <AlertTriangle className="w-3 h-3 text-red-400" />
                              <span className="text-text-secondary">{event.sourceNumber}</span>
                            </div>
                            <ArrowRight className="w-3 h-3 text-text-muted" />
                            <div className="flex items-center gap-2">
                              <Shield className="w-3 h-3 text-emerald-400" />
                              <span className="text-text-secondary">{event.targetNumber}</span>
                            </div>
                            <span className="text-text-muted ml-auto">by {event.performedBy}</span>
                          </div>
                          {event.metadata && Object.keys(event.metadata).length > 0 && (
                            <div className="mt-2 pt-2 border-t border-border flex flex-wrap gap-2">
                              {Object.entries(event.metadata).map(([key, value]) => (
                                <Badge key={key} color="slate" size="xs">{key}: {String(value)}</Badge>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </div>
        )}

        {/* CONFIG VIEW */}
        {activeView === 'config' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6">
            <div className="col-span-1 md:col-span-2 space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-medium text-text-primary">Auto-Generation Rules</h3>
                <Button variant="primary" size="sm" icon={<Plus className="w-4 h-4" onClick={() => toast.success('CAPA action recorded — assigned owner notified')} />}>
                  Add Rule
                </Button>
              </div>
              <div className="space-y-3">
                {configs.map(config => (
                  <Card 
                    key={config.id}
                    className={`cursor-pointer transition-all ${
                      selectedConfigId === config.id 
                        ? 'border-amber-500/50 bg-amber-500/5' 
                        : 'hover:border-amber-500/30'
                    }`}
                    onClick={() => setSelectedConfigId(config.id)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <Badge color={config.enabled ? 'emerald' : 'slate'} size="xs">
                              {config.enabled ? 'ENABLED' : 'DISABLED'}
                            </Badge>
                            <Badge color="amber" size="xs">{config.rule.replace(/-/g, ' ')}</Badge>
                          </div>
                          <h4 className="text-sm font-medium text-text-primary capitalize">
                            {config.rule.replace(/-/g, ' ')}
                          </h4>
                          <div className="text-xs text-text-muted mt-1">
                            Triggers on {config.triggerConditions.riskLevelThreshold}+ risks in {config.triggerConditions.categories.join(', ')}
                          </div>
                        </div>
                        <div className="flex flex-col items-end gap-2">
                          <span className="text-xs text-text-muted">{config.triggerCount} triggers</span>
                          <ChevronRight className="w-4 h-4 text-text-muted" />
                        </div>
                      </div>
                      <div className="mt-3 pt-3 border-t border-border flex items-center gap-4 text-xs text-text-muted">
                        <span>Creates: {config.capaTemplate.capaType} CAPA</span>
                        <span>Priority: {config.capaTemplate.priority}</span>
                        <span>Target: {config.capaTemplate.defaultTargetDays} days</span>
                        {config.triggerConditions.requiresApproval && (
                          <Badge color="purple" size="xs">Requires Approval</Badge>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
            
            {/* Config Detail */}
            <div>
              {selectedConfig ? (
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <Settings className="w-5 h-5 text-amber-400" />
                      <h3 className="text-sm font-medium text-text-primary">Rule Configuration</h3>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-text-secondary">Status</span>
                        <Badge color={selectedConfig.enabled ? 'emerald' : 'slate'} size="sm">
                          {selectedConfig.enabled ? 'Enabled' : 'Disabled'}
                        </Badge>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-2">Trigger Conditions</div>
                        <div className="p-3 bg-surface rounded-lg space-y-2">
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Risk Level Threshold</span>
                            {getRiskLevelBadge(selectedConfig.triggerConditions.riskLevelThreshold, 'xs')}
                          </div>
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Categories</span>
                            <div className="flex flex-wrap gap-1">
                              {selectedConfig.triggerConditions.categories.map(cat => (
                                <Badge key={cat} color="slate" size="xs">{cat}</Badge>
                              ))}
                            </div>
                          </div>
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Requires Approval</span>
                            <Badge color={selectedConfig.triggerConditions.requiresApproval ? 'purple' : 'slate'} size="xs">
                              {selectedConfig.triggerConditions.requiresApproval ? 'Yes' : 'No'}
                            </Badge>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="text-xs text-text-muted mb-2">CAPA Template</div>
                        <div className="p-3 bg-surface rounded-lg space-y-2">
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">CAPA Type</span>
                            <Badge 
                              color={selectedConfig.capaTemplate.capaType === 'corrective' ? 'orange' : selectedConfig.capaTemplate.capaType === 'preventive' ? 'blue' : 'purple'} 
                              size="xs"
                            >
                              {selectedConfig.capaTemplate.capaType}
                            </Badge>
                          </div>
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Priority</span>
                            <Badge 
                              color={selectedConfig.capaTemplate.priority === 'critical' ? 'red' : selectedConfig.capaTemplate.priority === 'high' ? 'orange' : 'amber'} 
                              size="xs"
                            >
                              {selectedConfig.capaTemplate.priority}
                            </Badge>
                          </div>
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Target Days</span>
                            <span className="text-text-primary">{selectedConfig.capaTemplate.defaultTargetDays} days</span>
                          </div>
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-secondary">Assign to Risk Owner</span>
                            <Badge color={selectedConfig.capaTemplate.assignToRiskOwner ? 'emerald' : 'slate'} size="xs">
                              {selectedConfig.capaTemplate.assignToRiskOwner ? 'Yes' : 'No'}
                            </Badge>
                          </div>
                        </div>
                      </div>
                      <div className="pt-4 border-t border-border space-y-2">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-text-muted">Total Triggers</span>
                          <span className="text-text-primary font-medium">{selectedConfig.triggerCount}</span>
                        </div>
                        {selectedConfig.lastTriggered && (
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-text-muted">Last Triggered</span>
                            <span className="text-text-secondary">{new Date(selectedConfig.lastTriggered).toLocaleString()}</span>
                          </div>
                        )}
                      </div>
                      <div className="flex gap-2 pt-4">
                        <Button variant="outline" size="sm" className="flex-1" icon={<Edit3 className="w-4 h-4" onClick={() => toast.success('CAPA action recorded — assigned owner notified')} />}>
                          Edit
                        </Button>
                        <Button
                          onClick={() => toast.success('CAPA action recorded — assigned owner notified')}
                          variant={selectedConfig.enabled ? 'outline' : 'primary'} 
                          size="sm" 
                          className="flex-1"
                          icon={selectedConfig.enabled ? <XCircle className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4" />}
                        >
                          {selectedConfig.enabled ? 'Disable' : 'Enable'}
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card>
                  <CardContent className="p-8 text-center">
                    <Settings className="w-12 h-12 text-text-muted mx-auto mb-3" />
                    <div className="text-sm text-text-muted">Select a rule to view configuration</div>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Named export for compatibility
export default RiskCAPAIntegrationDashboard;
