
// ============================================================================
// Aggregate Safety Reports Types - v55
// DSUR, PBRER, PSUR generation with signal integration, cumulative safety data,
// and cross-study safety analysis
// ============================================================================

// ============================================================================
// REPORT FRAMEWORK TYPES
// ============================================================================

export type AggregateReportType = 
  | 'DSUR'      // Development Safety Update Report (ICH E2F)
  | 'PBRER'     // Periodic Benefit-Risk Evaluation Report (ICH E2C R2)
  | 'PSUR'      // Periodic Safety Update Report (pre-ICH E2C)
  | 'PADER'     // Post-Authorization Drug Event Report
  | 'IND-Annual' // FDA IND Annual Report
  | 'SUSAR'     // Suspected Unexpected Serious Adverse Reaction summary
  | 'Line-Listing'; // Raw case line listing

export type ReportGenerationStatus = 
  | 'not-started'
  | 'data-collection'
  | 'analysis'
  | 'drafting'
  | 'medical-review'
  | 'quality-review'
  | 'sign-off'
  | 'finalized'
  | 'submitted';

export type ReportPriority = 'routine' | 'high' | 'urgent' | 'emergency';

export type SubmissionRegion = 
  | 'FDA'
  | 'EMA'
  | 'PMDA'
  | 'NMPA'
  | 'Health-Canada'
  | 'TGA'
  | 'MHRA'
  | 'Swissmedic'
  | 'Other';

export interface ReportingPeriod {
  startDate: string;
  endDate: string;
  dataLockPoint: string;
  previousDataLockPoint?: string;
}

export interface ReportConfiguration {
  id: string;
  reportType: AggregateReportType;
  
  // Scope
  programId: string;
  studyIds: string[]; // Empty = all studies in program
  productName: string;
  activeSubstance: string;
  
  // Period
  reportingPeriod: ReportingPeriod;
  reportingCycle: 'annual' | 'semi-annual' | 'quarterly' | 'ad-hoc';
  
  // Submission targets
  targetRegions: SubmissionRegion[];
  dueDate: string;
  submissionDeadline: string;
  
  // Content options
  includeLineListings: boolean;
  includeNarratives: boolean;
  includeSummaryTables: boolean;
  includeSignalSection: boolean;
  includeBenefitRiskAssessment: boolean;
  
  // Thresholds
  seriousnessThreshold: 'all' | 'serious-only' | 'fatal-only';
  relatednessThreshold: 'all' | 'related-only' | 'possibly-related';
  
  // Templates
  templateId?: string;
  customSections?: string[];
  
  createdAt: string;
  createdBy: string;
  updatedAt: string;
}

// ============================================================================
// DSUR - DEVELOPMENT SAFETY UPDATE REPORT (ICH E2F)
// ============================================================================

export type DSURSection = 
  | 'executive-summary'
  | 'introduction'
  | 'worldwide-marketing-status'
  | 'actions-taken'
  | 'changes-to-reference-safety'
  | 'patient-exposure'
  | 'individual-case-summaries'
  | 'studies-ongoing'
  | 'safety-findings-clinical-trials'
  | 'safety-findings-non-interventional'
  | 'safety-related-findings-other'
  | 'non-clinical-data'
  | 'literature'
  | 'other-clinical-trial-safety-data'
  | 'signals-new-identified'
  | 'signals-ongoing'
  | 'signals-closed'
  | 'benefit-risk-evaluation'
  | 'summary-new-information'
  | 'conclusions'
  | 'appendices';

export interface DSURReport {
  id: string;
  configId: string;
  programId: string;
  version: number;
  
  // Identification
  reportTitle: string;
  developmentInternationalBirthDate: string;
  reportNumber: string;
  coveringPeriod: ReportingPeriod;
  
  // Status
  status: ReportGenerationStatus;
  priority: ReportPriority;
  
  // Sections with content
  sections: DSURSectionContent[];
  
  // Data summaries
  exposureSummary: PatientExposureSummary;
  safetyDataSummary: SafetyDataSummary;
  signalSummary: SignalSummary;
  
  // Quality
  completenessScore: number;
  qualityIssues: ReportQualityIssue[];
  
  // Workflow
  currentReviewer?: string;
  reviewHistory: ReportReviewEntry[];
  signatureBlock: SignatureBlock;
  
  // Timestamps
  dataLockDate: string;
  draftCompletedDate?: string;
  finalizedDate?: string;
  submittedDate?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DSURSectionContent {
  sectionId: DSURSection;
  sectionNumber: string;
  sectionTitle: string;
  
  // Content
  content: string;
  tables: ReportTable[];
  figures: ReportFigure[];
  
  // Status
  status: 'not-started' | 'draft' | 'review' | 'approved';
  lastEditedBy?: string;
  lastEditedAt?: string;
  
  // Auto-generated flag
  autoGenerated: boolean;
  sourceDataTimestamp?: string;
}

// ============================================================================
// PBRER - PERIODIC BENEFIT-RISK EVALUATION REPORT (ICH E2C R2)
// ============================================================================

export type PBRERSection =
  | 'executive-summary'
  | 'introduction'
  | 'worldwide-marketing-authorization-status'
  | 'actions-taken-reporting-period'
  | 'changes-to-reference-safety-information'
  | 'estimated-exposure'
  | 'data-in-summary-tabulations'
  | 'summaries-of-significant-safety-findings'
  | 'signal-and-risk-evaluation'
  | 'benefit-evaluation'
  | 'integrated-benefit-risk-analysis'
  | 'conclusions-and-actions'
  | 'appendices';

export interface PBRERReport {
  id: string;
  configId: string;
  programId: string;
  applicationIds: string[];
  version: number;
  
  // Identification
  reportTitle: string;
  internationalBirthDate: string;
  dataPeriod: ReportingPeriod;
  
  // Reference info
  approvedIndications: string[];
  referenceProduct: string;
  marketedRegions: SubmissionRegion[];
  
  // Status
  status: ReportGenerationStatus;
  priority: ReportPriority;
  
  // Sections
  sections: PBRERSectionContent[];
  
  // Data
  exposureData: MarketExposureData;
  safetyProfile: SafetyProfileSummary;
  benefitAssessment: BenefitAssessment;
  riskAssessment: RiskAssessment;
  benefitRiskConclusion: BenefitRiskConclusion;
  
  // Signal tracking
  signalsEvaluated: SignalEvaluationSummary[];
  
  // Workflow
  reviewCycle: ReviewCycle;
  signatureBlock: SignatureBlock;
  
  createdAt: string;
  updatedAt: string;
}

export interface PBRERSectionContent {
  sectionId: PBRERSection;
  sectionNumber: string;
  sectionTitle: string;
  content: string;
  tables: ReportTable[];
  figures: ReportFigure[];
  status: 'not-started' | 'draft' | 'review' | 'approved';
  autoGenerated: boolean;
  lastEditedBy?: string;
  lastEditedAt?: string;
}

// ============================================================================
// PSUR - PERIODIC SAFETY UPDATE REPORT
// ============================================================================

export type PSURSection =
  | 'introduction'
  | 'worldwide-marketing-status'
  | 'actions-taken-for-safety'
  | 'changes-to-reference-product'
  | 'patient-exposure'
  | 'presentation-of-individual-case-histories'
  | 'studies'
  | 'other-information'
  | 'overall-safety-evaluation'
  | 'conclusion';

export interface PSURReport {
  id: string;
  configId: string;
  programId: string;
  version: number;
  
  reportTitle: string;
  dataPeriod: ReportingPeriod;
  
  status: ReportGenerationStatus;
  sections: PSURSectionContent[];
  
  exposureSummary: PatientExposureSummary;
  caseAnalysis: CaseAnalysisSummary;
  
  reviewCycle: ReviewCycle;
  signatureBlock: SignatureBlock;
  
  createdAt: string;
  updatedAt: string;
}

export interface PSURSectionContent {
  sectionId: PSURSection;
  sectionNumber: string;
  sectionTitle: string;
  content: string;
  tables: ReportTable[];
  status: 'not-started' | 'draft' | 'review' | 'approved';
  autoGenerated: boolean;
}

// ============================================================================
// EXPOSURE DATA TYPES
// ============================================================================

export interface PatientExposureSummary {
  id: string;
  reportId: string;
  calculatedAt: string;
  
  // Clinical trial exposure
  clinicalTrialExposure: ClinicalTrialExposure;
  
  // Post-marketing exposure (if applicable)
  postMarketingExposure?: PostMarketingExposure;
  
  // Combined
  totalPatientsExposed: number;
  totalPatientYears: number;
  
  // By demographic
  exposureByAge: ExposureBreakdown[];
  exposureBySex: ExposureBreakdown[];
  exposureByRegion: ExposureBreakdown[];
  exposureByDose: ExposureBreakdown[];
  exposureByDuration: ExposureBreakdown[];
  
  // Methodology notes
  calculationMethod: string;
  dataLimitations: string[];
}

export interface ClinicalTrialExposure {
  // By study
  studyExposures: StudyExposure[];
  
  // Totals
  totalSubjectsExposed: number;
  totalSubjectYears: number;
  
  // Active vs comparator
  activeArmExposure: number;
  comparatorArmExposure: number;
  
  // Treatment duration
  meanDurationWeeks: number;
  medianDurationWeeks: number;
  maxDurationWeeks: number;
}

export interface StudyExposure {
  studyId: string;
  studyName: string;
  phase: string;
  
  subjectsExposed: number;
  subjectYears: number;
  
  treatmentDurationMean: number;
  treatmentDurationMedian: number;
  
  ongoingSubjects: number;
  completedSubjects: number;
  discontinuedSubjects: number;
}

export interface PostMarketingExposure {
  estimatedPatients: number;
  estimatedPatientYears: number;
  
  // Source of estimates
  estimationMethod: 'sales-data' | 'prescription-data' | 'registry' | 'other';
  dataSource: string;
  
  // By region
  exposureByRegion: RegionExposure[];
  
  // Confidence
  confidenceLevel: 'high' | 'medium' | 'low';
  limitations: string[];
}

export interface RegionExposure {
  region: SubmissionRegion;
  country?: string;
  estimatedPatients: number;
  estimatedPatientYears: number;
  marketingStartDate: string;
}

export interface ExposureBreakdown {
  category: string;
  value: string;
  count: number;
  percentage: number;
  patientYears?: number;
}

export interface MarketExposureData {
  cumulativeExposure: number;
  exposureThisPeriod: number;
  exposureUnits: 'patients' | 'patient-years' | 'prescriptions';
  
  byIndication: ExposureBreakdown[];
  byFormulation: ExposureBreakdown[];
  byRegion: ExposureBreakdown[];
}

// ============================================================================
// SAFETY DATA TYPES
// ============================================================================

export interface SafetyDataSummary {
  id: string;
  reportId: string;
  dataLockPoint: string;
  
  // Case counts
  totalCases: number;
  newCasesThisPeriod: number;
  seriousCases: number;
  fatalCases: number;
  
  // By source
  clinicalTrialCases: number;
  spontaneousCases: number;
  literatureCases: number;
  regulatoryCases: number;
  
  // By relatedness
  relatedCases: number;
  possiblyRelatedCases: number;
  unrelatedCases: number;
  notAssessable: number;
  
  // By listedness
  listedCases: number;
  unlistedCases: number;
  
  // Top events
  topAdverseEvents: AdverseEventSummary[];
  topSOCs: SOCSummary[];
  
  // SUSAR summary
  susarCount: number;
  susarsByType: SUSARBreakdown[];
  
  // Comparative data (if available)
  comparativeAnalysis?: ComparativeAnalysis;
}

export interface AdverseEventSummary {
  preferredTerm: string;
  soc: string;
  
  totalCases: number;
  seriousCases: number;
  fatalCases: number;
  
  incidenceRate?: number;
  comparatorRate?: number;
  
  relatedCases: number;
  
  trend: 'increasing' | 'stable' | 'decreasing';
  newThisPeriod: number;
}

export interface SOCSummary {
  socName: string;
  socCode: string;
  
  totalCases: number;
  seriousCases: number;
  fatalCases: number;
  
  topPreferredTerms: string[];
  percentOfTotal: number;
}

export interface SUSARBreakdown {
  category: string;
  count: number;
  percentage: number;
  listOfPTs: string[];
}

export interface ComparativeAnalysis {
  treatmentGroup: GroupAnalysis;
  comparatorGroup: GroupAnalysis;
  
  relativeRisk?: number;
  riskDifference?: number;
  confidenceInterval: [number, number];
  pValue?: number;
}

export interface GroupAnalysis {
  groupName: string;
  totalSubjects: number;
  totalEvents: number;
  incidenceRate: number;
  seriousRate: number;
}

// ============================================================================
// SIGNAL TYPES
// ============================================================================

export interface SignalSummary {
  reportId: string;
  evaluationDate: string;
  
  // Signal counts
  newSignalsIdentified: number;
  signalsUnderEvaluation: number;
  signalsConfirmed: number;
  signalsRefuted: number;
  signalsClosed: number;
  
  // Details
  newSignals: SignalDetail[];
  ongoingSignals: SignalDetail[];
  closedSignals: SignalDetail[];
  
  // Methodology
  detectionMethods: string[];
  evaluationProcess: string;
}

export interface SignalDetail {
  signalId: string;
  signalName: string;
  preferredTerm: string;
  soc: string;
  
  detectionDate: string;
  detectionMethod: string;
  
  status: 'new' | 'under-evaluation' | 'confirmed' | 'refuted' | 'closed';
  priority: 'high' | 'medium' | 'low';
  
  // Data supporting signal
  observedCases: number;
  expectedCases?: number;
  disproportionalityScore?: number;
  
  // Evaluation
  evaluationSummary?: string;
  conclusion?: string;
  recommendedActions?: string[];
  
  // Impact
  labelingImpact?: string;
  riskMinimization?: string;
}

export interface SignalEvaluationSummary {
  signalId: string;
  signalName: string;
  evaluationStatus: 'completed' | 'ongoing' | 'pending';
  conclusion: 'signal-confirmed' | 'signal-refuted' | 'further-data-needed';
  actionsRequired: string[];
}

// ============================================================================
// BENEFIT-RISK ASSESSMENT TYPES
// ============================================================================

export interface BenefitAssessment {
  id: string;
  reportId: string;
  assessmentDate: string;
  
  // Approved indications
  indications: IndicationBenefit[];
  
  // Overall benefit
  overallBenefitRating: 'well-established' | 'established' | 'emerging' | 'uncertain';
  benefitSummary: string;
  
  // Evidence
  efficacyData: EfficacyDataSummary[];
  clinicalRelevance: string;
  
  // Changes this period
  newEfficacyData: boolean;
  benefitChanges: string[];
}

export interface IndicationBenefit {
  indication: string;
  approvalStatus: 'approved' | 'under-review' | 'investigational';
  
  primaryEndpoint: string;
  treatmentEffect: string;
  clinicalSignificance: string;
  
  strengthOfEvidence: 'strong' | 'moderate' | 'limited';
  populationBenefit: string;
}

export interface EfficacyDataSummary {
  studyId: string;
  studyType: string;
  primaryEndpoint: string;
  result: string;
  statisticalSignificance: boolean;
  clinicalRelevance: string;
}

export interface RiskAssessment {
  id: string;
  reportId: string;
  assessmentDate: string;
  
  // Identified risks
  identifiedRisks: IdentifiedRisk[];
  potentialRisks: PotentialRisk[];
  missingInformation: MissingInformation[];
  
  // Overall assessment
  overallRiskProfile: 'favorable' | 'acceptable' | 'unfavorable' | 'uncertain';
  riskSummary: string;
  
  // Changes this period
  newRisksIdentified: boolean;
  riskProfileChanges: string[];
  
  // Risk minimization
  riskMinimizationMeasures: RiskMinimizationMeasure[];
}

export interface IdentifiedRisk {
  riskId: string;
  riskName: string;
  preferredTerm: string;
  
  category: 'important-identified' | 'identified';
  frequency: 'very-common' | 'common' | 'uncommon' | 'rare' | 'very-rare';
  
  seriousness: 'serious' | 'non-serious';
  reversibility: 'reversible' | 'partially-reversible' | 'irreversible' | 'unknown';
  
  mechanism?: string;
  riskFactors: string[];
  
  currentMitigation: string;
  labelingStatus: 'in-label' | 'proposed-update' | 'not-in-label';
  
  evidenceSummary: string;
  incidenceData?: string;
}

export interface PotentialRisk {
  riskId: string;
  riskName: string;
  
  basisForConcern: string;
  availableData: string;
  
  furtherDataNeeded: string;
  monitoringPlan?: string;
}

export interface MissingInformation {
  category: string;
  description: string;
  
  population?: string;
  
  planToAddress: string;
  expectedTimeline?: string;
}

export interface RiskMinimizationMeasure {
  measureType: 'routine' | 'additional';
  measureName: string;
  description: string;
  
  targetRisk: string;
  effectiveness: 'effective' | 'partially-effective' | 'under-evaluation' | 'unknown';
  
  implementationStatus: 'implemented' | 'planned' | 'under-development';
  regions: SubmissionRegion[];
}

export interface BenefitRiskConclusion {
  reportId: string;
  assessmentDate: string;
  
  // Overall conclusion
  overallConclusion: 'favorable' | 'favorable-with-monitoring' | 'uncertain' | 'unfavorable';
  conclusionText: string;
  
  // By indication
  indicationConclusions: IndicationBenefitRisk[];
  
  // Changes from previous
  changesFromPrevious: string[];
  
  // Recommendations
  recommendations: string[];
  proposedActions: ProposedAction[];
}

export interface IndicationBenefitRisk {
  indication: string;
  benefitRating: 'well-established' | 'established' | 'emerging' | 'uncertain';
  riskRating: 'favorable' | 'acceptable' | 'unfavorable';
  overallConclusion: 'positive' | 'positive-with-conditions' | 'uncertain' | 'negative';
  keyConsiderations: string[];
}

export interface ProposedAction {
  actionType: 'labeling-update' | 'risk-minimization' | 'further-study' | 'restriction' | 'communication' | 'other';
  description: string;
  targetRegions: SubmissionRegion[];
  proposedTimeline: string;
  rationale: string;
}

// ============================================================================
// SAFETY PROFILE & CUMULATIVE DATA
// ============================================================================

export interface SafetyProfileSummary {
  productId: string;
  assessmentDate: string;
  
  // Known safety profile
  knownAdverseReactions: KnownAdverseReaction[];
  
  // Special populations
  specialPopulations: SpecialPopulationData[];
  
  // Drug interactions
  knownInteractions: DrugInteraction[];
  
  // Overdose data
  overdoseExperience: OverdoseData;
  
  // Abuse/dependence
  abuseData?: AbuseData;
}

export interface KnownAdverseReaction {
  preferredTerm: string;
  soc: string;
  
  frequencyCategory: 'very-common' | 'common' | 'uncommon' | 'rare' | 'very-rare' | 'not-known';
  frequencyRate?: number;
  
  seriousness: 'serious' | 'non-serious' | 'both';
  outcome: 'recoverable' | 'persistent' | 'variable';
  
  labelingStatus: 'in-label' | 'proposed' | 'under-evaluation';
  firstIdentified: string;
  
  clinicalDescription?: string;
  management?: string;
}

export interface SpecialPopulationData {
  population: 'pediatric' | 'geriatric' | 'pregnant' | 'lactating' | 'renal-impairment' | 'hepatic-impairment' | 'other';
  populationDescription: string;
  
  dataAvailable: boolean;
  exposureCount?: number;
  
  safetyFindings: string;
  recommendations: string;
  
  dataGaps?: string;
}

export interface DrugInteraction {
  interactingDrug: string;
  interactionType: 'pharmacokinetic' | 'pharmacodynamic' | 'both';
  
  clinicalSignificance: 'major' | 'moderate' | 'minor';
  mechanism: string;
  recommendation: string;
  
  inLabel: boolean;
}

export interface OverdoseData {
  casesReported: number;
  maxDoseReported?: string;
  
  clinicalPresentation: string;
  outcomes: string;
  management: string;
  
  antidoteAvailable: boolean;
  antidoteDetails?: string;
}

export interface AbuseData {
  scheduleStatus: string;
  abuseIndicators: boolean;
  
  casesReported: number;
  patterns: string;
  
  mitigationMeasures: string[];
}

// ============================================================================
// CROSS-STUDY SAFETY ANALYSIS
// ============================================================================

export interface CrossStudyAnalysis {
  id: string;
  programId: string;
  analysisDate: string;
  analysisType: 'pooled' | 'meta-analysis' | 'cross-study-comparison';
  
  // Studies included
  includedStudies: IncludedStudySummary[];
  
  // Pooled exposure
  totalExposure: number;
  totalPatientYears: number;
  
  // Pooled safety
  pooledSafetyResults: PooledSafetyResult[];
  
  // Cross-study signals
  emergingSignals: CrossStudySignal[];
  
  // Heterogeneity assessment
  heterogeneityAssessment: HeterogeneityAssessment;
  
  // Conclusions
  keyFindings: string[];
  limitations: string[];
  recommendations: string[];
  
  createdBy: string;
  createdAt: string;
}

export interface IncludedStudySummary {
  studyId: string;
  studyName: string;
  phase: string;
  
  design: string;
  population: string;
  
  totalSubjects: number;
  treatmentArmSubjects: number;
  
  primaryEndpoint: string;
  studyStatus: 'ongoing' | 'completed' | 'terminated';
  
  weight?: number; // For meta-analysis
}

export interface PooledSafetyResult {
  preferredTerm: string;
  soc: string;
  
  // Pooled rates
  treatmentRate: number;
  treatmentEvents: number;
  treatmentExposed: number;
  
  comparatorRate?: number;
  comparatorEvents?: number;
  comparatorExposed?: number;
  
  // Effect estimate
  relativeRisk?: number;
  riskRatioLower?: number;
  riskRatioUpper?: number;
  
  pValue?: number;
  heterogeneityI2?: number;
  
  // Assessment
  signalFlag: boolean;
  clinicalAssessment: string;
}

export interface CrossStudySignal {
  signalId: string;
  preferredTerm: string;
  
  studiesWithSignal: string[];
  combinedStrength: 'strong' | 'moderate' | 'weak';
  
  pooledIncidence: number;
  expectedIncidence?: number;
  
  recommendation: string;
}

export interface HeterogeneityAssessment {
  overallI2: number;
  heterogeneityPValue: number;
  
  interpretation: 'low' | 'moderate' | 'high';
  
  sourcesOfHeterogeneity: string[];
  sensitivityAnalyses: SensitivityAnalysis[];
}

export interface SensitivityAnalysis {
  analysisName: string;
  description: string;
  result: string;
  impactOnConclusion: 'no-change' | 'minor-change' | 'major-change';
}

// ============================================================================
// REPORT WORKFLOW & QUALITY
// ============================================================================

export interface ReviewCycle {
  currentPhase: 'drafting' | 'internal-review' | 'medical-review' | 'quality-review' | 'management-review' | 'final';
  
  reviewers: ReportReviewer[];
  
  targetCompletionDate: string;
  currentProgressPercent: number;
  
  blockers: string[];
}

export interface ReportReviewer {
  userId: string;
  userName: string;
  role: 'author' | 'medical-reviewer' | 'quality-reviewer' | 'approver' | 'signatory';
  
  assignedSections: string[];
  reviewStatus: 'pending' | 'in-progress' | 'completed' | 'approved' | 'rejected';
  
  commentsCount: number;
  lastActivityDate?: string;
}

export interface ReportReviewEntry {
  id: string;
  reviewerId: string;
  reviewerName: string;
  reviewerRole: string;
  
  action: 'submitted' | 'reviewed' | 'approved' | 'rejected' | 'comment' | 'revision-requested';
  comments?: string;
  
  sectionsReviewed: string[];
  timestamp: string;
}

export interface SignatureBlock {
  requiredSignatures: RequiredSignature[];
  signatures: ReportSignature[];
  
  allSigned: boolean;
  signatureDeadline?: string;
}

export interface RequiredSignature {
  role: 'qualified-person' | 'medical-officer' | 'regulatory-affairs' | 'quality-assurance' | 'executive';
  roleDescription: string;
  required: boolean;
  order: number;
}

export interface ReportSignature {
  signatureId: string;
  role: string;
  
  signedBy: string;
  signedByTitle: string;
  
  signedDate: string;
  signatureType: 'electronic' | 'wet';
  
  comments?: string;
}

export interface ReportQualityIssue {
  issueId: string;
  severity: 'critical' | 'major' | 'minor';
  
  section: string;
  description: string;
  
  status: 'open' | 'in-progress' | 'resolved' | 'accepted';
  assignee?: string;
  
  detectedAt: string;
  resolvedAt?: string;
}

// ============================================================================
// REPORT CONTENT ELEMENTS
// ============================================================================

export interface ReportTable {
  tableId: string;
  tableNumber: string;
  tableTitle: string;
  
  columns: TableColumn[];
  rows: TableRow[];
  
  footnotes: string[];
  source: string;
  
  autoGenerated: boolean;
  lastUpdated: string;
}

export interface TableColumn {
  columnId: string;
  header: string;
  dataType: 'text' | 'number' | 'percentage' | 'date';
  width?: string;
}

export interface TableRow {
  rowId: string;
  cells: TableCell[];
  isHeader?: boolean;
  isTotal?: boolean;
}

export interface TableCell {
  columnId: string;
  value: string;
  highlighted?: boolean;
  footnoteRef?: string;
}

export interface ReportFigure {
  figureId: string;
  figureNumber: string;
  figureTitle: string;
  
  figureType: 'chart' | 'diagram' | 'image' | 'forest-plot' | 'kaplan-meier';
  
  dataSource: string;
  imageUrl?: string;
  chartConfig?: object;
  
  caption: string;
  footnotes: string[];
  
  autoGenerated: boolean;
}

// ============================================================================
// LINE LISTING TYPES
// ============================================================================

export interface LineListingConfig {
  id: string;
  reportId: string;
  
  listingType: 'all-cases' | 'serious-only' | 'susar' | 'fatal' | 'custom';
  
  // Columns to include
  columns: LineListingColumn[];
  
  // Filters
  seriousnessFilter: 'all' | 'serious' | 'non-serious';
  relatednessFilter: 'all' | 'related' | 'possibly-related';
  outcomeFilter: string[];
  sourceFilter: string[];
  
  // Sorting
  sortBy: string;
  sortOrder: 'asc' | 'desc';
  
  // Blinding
  preserveBlinding: boolean;
  
  createdAt: string;
}

export interface LineListingColumn {
  columnId: string;
  fieldName: string;
  displayName: string;
  width: number;
  required: boolean;
  order: number;
}

export interface LineListingEntry {
  caseId: string;
  caseNumber: string;
  
  // Patient
  patientId?: string;
  age?: number;
  sex?: string;
  country?: string;
  
  // Event
  preferredTerm: string;
  soc: string;
  onsetDate?: string;
  outcomeDate?: string;
  
  // Characteristics
  seriousness: string;
  seriousnessCriteria?: string[];
  outcome: string;
  relatedness: string;
  listedness: string;
  
  // Study (if clinical trial)
  studyId?: string;
  treatmentArm?: string;
  
  // Narrative snippet
  narrativeSnippet?: string;
  
  // Source
  source: string;
  receiptDate: string;
}

export interface GeneratedLineListing {
  id: string;
  configId: string;
  reportId: string;
  
  generatedAt: string;
  dataLockPoint: string;
  
  totalCases: number;
  entries: LineListingEntry[];
  
  // Export options
  exportFormats: ('pdf' | 'excel' | 'csv')[];
}

// ============================================================================
// CASE ANALYSIS SUMMARY
// ============================================================================

export interface CaseAnalysisSummary {
  reportId: string;
  analysisDate: string;
  
  // Overall counts
  totalCasesAnalyzed: number;
  newCasesThisPeriod: number;
  
  // By seriousness
  seriousCases: number;
  nonSeriousCases: number;
  fatalCases: number;
  
  // By causality
  relatedCases: number;
  possiblyRelatedCases: number;
  unlikelyRelatedCases: number;
  notRelatedCases: number;
  notAssessableCases: number;
  
  // By listedness
  listedReactions: number;
  unlistedReactions: number;
  
  // Notable cases
  notableCases: NotableCase[];
  
  // Trends
  trendsIdentified: string[];
}

export interface NotableCase {
  caseId: string;
  caseNumber: string;
  
  reason: 'first-occurrence' | 'unexpected-severity' | 'fatal' | 'cluster' | 'regulatory-interest' | 'other';
  
  eventTerm: string;
  brief: string;
  
  medicalAssessment: string;
  followUpStatus: 'complete' | 'ongoing' | 'requested';
}

// ============================================================================
// STATE & STORE TYPES
// ============================================================================

export type AggregateReportView = 
  | 'report-list'
  | 'report-wizard'
  | 'dsur-editor'
  | 'pbrer-editor'
  | 'psur-editor'
  | 'exposure-analysis'
  | 'safety-summary'
  | 'signal-review'
  | 'benefit-risk'
  | 'cross-study'
  | 'line-listing'
  | 'review-workflow';

export interface AggregateReportFilters {
  reportTypes: AggregateReportType[];
  statuses: ReportGenerationStatus[];
  programIds: string[];
  dateRange: {
    start: string;
    end: string;
  } | null;
  searchTerm: string;
}

export interface AggregateReportState {
  // Data
  configurations: ReportConfiguration[];
  dsurReports: DSURReport[];
  pbrerReports: PBRERReport[];
  psurReports: PSURReport[];
  crossStudyAnalyses: CrossStudyAnalysis[];
  lineListings: GeneratedLineListing[];
  
  // Selection
  selectedConfigId: string | null;
  selectedReportId: string | null;
  selectedAnalysisId: string | null;
  
  // UI
  activeView: AggregateReportView;
  filters: AggregateReportFilters;
  isLoading: boolean;
  error: string | null;
  
  // Wizard state
  wizardStep: number;
  wizardDraft: Partial<ReportConfiguration> | null;
}

export interface AggregateReportActions {
  // Configuration
  createConfiguration: (config: Omit<ReportConfiguration, 'id' | 'createdAt' | 'updatedAt'>, createdBy: string) => string;
  updateConfiguration: (id: string, updates: Partial<ReportConfiguration>) => void;
  deleteConfiguration: (id: string) => void;
  
  // DSUR
  generateDSUR: (configId: string, generatedBy: string) => string;
  updateDSURSection: (reportId: string, sectionId: DSURSection, content: Partial<DSURSectionContent>) => void;
  submitDSURForReview: (reportId: string, reviewerId: string) => void;
  approveDSURSection: (reportId: string, sectionId: DSURSection, reviewerId: string) => void;
  finalizeDSUR: (reportId: string) => void;
  
  // PBRER
  generatePBRER: (configId: string, generatedBy: string) => string;
  updatePBRERSection: (reportId: string, sectionId: PBRERSection, content: Partial<PBRERSectionContent>) => void;
  updateBenefitRisk: (reportId: string, benefitRisk: Partial<BenefitRiskConclusion>) => void;
  finalizePBRER: (reportId: string) => void;
  
  // PSUR
  generatePSUR: (configId: string, generatedBy: string) => string;
  updatePSURSection: (reportId: string, sectionId: PSURSection, content: Partial<PSURSectionContent>) => void;
  finalizePSUR: (reportId: string) => void;
  
  // Exposure analysis
  calculateExposure: (reportId: string) => PatientExposureSummary;
  
  // Safety summary
  generateSafetyDataSummary: (reportId: string) => SafetyDataSummary;
  
  // Signal integration
  generateSignalSummary: (reportId: string, programId: string) => SignalSummary;
  
  // Cross-study analysis
  runCrossStudyAnalysis: (programId: string, studyIds: string[], analysisType: CrossStudyAnalysis['analysisType'], userId: string) => string;
  
  // Line listings
  generateLineListing: (configId: string, reportId: string) => string;
  
  // Review workflow
  addReviewer: (reportId: string, reviewer: Omit<ReportReviewer, 'reviewStatus' | 'commentsCount' | 'lastActivityDate'>) => void;
  submitReview: (reportId: string, reviewerId: string, action: ReportReviewEntry['action'], comments?: string) => void;
  addSignature: (reportId: string, signature: Omit<ReportSignature, 'signatureId'>) => void;
  
  // UI actions
  setActiveView: (view: AggregateReportView) => void;
  setFilters: (filters: Partial<AggregateReportFilters>) => void;
  selectConfig: (id: string | null) => void;
  selectReport: (id: string | null) => void;
  selectAnalysis: (id: string | null) => void;
  
  // Wizard
  setWizardStep: (step: number) => void;
  updateWizardDraft: (updates: Partial<ReportConfiguration>) => void;
  clearWizardDraft: () => void;
  
  // Data loading
  loadReportData: (programId: string) => Promise<void>;
  
  // Clear
  clearAll: () => void;
}
