

/**
 * R&D Archives Repository Store
 * v0.13.80 - Audit Trail Tab (COMPLETE MODULE)
 * 
 * Zustand store for managing R&D archive data across all tabs
 */

import { create } from 'zustand';
import {
  ArchivesState,
  ArchivesActions,
  ArchiveTab,
  ArchiveFilters,
  ArchivedDocument,
  ArchivedStudy,
  Specimen,
  RetentionSchedule,
  ArchiveAuditEntry,
  ArchiveDashboardMetrics,
  ArchiveActionItem,
  ArchiveHealthMetrics,
  ArchiveTypeBreakdown,
  RecentArchiveActivity,
} from './archivesTypes';

// ============================================================================
// Mock Data - Dashboard Metrics
// ============================================================================

const MOCK_METRICS: ArchiveDashboardMetrics = {
  totalDocuments: 2847,
  totalStudies: 156,
  totalSpecimens: 12450,
  totalSchedules: 24,
  
  pendingReviews: 23,
  pendingDestructions: 8,
  legalHolds: 3,
  retrievalRequests: 5,
  
  storageUsedTB: 45.2,
  storageCapacityTB: 100,
  
  complianceScore: 94,
  overdueReviews: 4,
  expiringRetention30Days: 12,
};

// ============================================================================
// Mock Data - Action Items (8 items per plan)
// ============================================================================

const MOCK_ACTION_ITEMS: ArchiveActionItem[] = [
  {
    id: 'act-001',
    type: 'review',
    priority: 'high',
    title: 'Periodic Review Due: LIG-2019-CSR-001',
    description: 'Annual archive review overdue by 14 days',
    dueDate: '2025-12-20',
    assignedTo: 'Jennifer Walsh',
    recordType: 'document',
    recordId: 'doc-001',
  },
  {
    id: 'act-002',
    type: 'destruction',
    priority: 'medium',
    title: 'Retention Expired: 8 documents ready for destruction',
    description: 'Training records from 2010 - retention period complete',
    dueDate: '2026-01-15',
    assignedTo: 'Michael Torres',
    recordType: 'document',
    recordId: 'batch-destruction-001',
  },
  {
    id: 'act-003',
    type: 'legal-hold',
    priority: 'critical',
    title: 'Legal Hold Applied: LIG-301 Study Data',
    description: 'All LIG-301 materials under litigation hold per Legal',
    recordType: 'study',
    recordId: 'study-003',
  },
  {
    id: 'act-004',
    type: 'retrieval',
    priority: 'high',
    title: 'Retrieval Request: FDA Pre-NDA Meeting Package',
    description: 'Regulatory Affairs requesting 2023 meeting materials',
    dueDate: '2026-01-10',
    assignedTo: 'Sarah Chen',
    recordType: 'document',
    recordId: 'doc-015',
  },
  {
    id: 'act-005',
    type: 'expiring',
    priority: 'medium',
    title: '12 Specimens Approaching Expiry',
    description: 'Stability samples from LIG-201 expire in 30 days',
    dueDate: '2026-02-07',
    recordType: 'specimen',
    recordId: 'specimen-batch-001',
  },
  {
    id: 'act-006',
    type: 'review',
    priority: 'medium',
    title: 'Quarterly GLP Archive Review',
    description: 'Q1 2026 review for 21 CFR Part 58.195 compliance',
    dueDate: '2026-01-31',
    assignedTo: 'Robert Kim',
    recordType: 'study',
    recordId: 'glp-review-q1',
  },
  {
    id: 'act-007',
    type: 'retrieval',
    priority: 'low',
    title: 'Research Request: Historical Protocol Templates',
    description: 'R&D requesting Phase I protocol templates from 2018-2020',
    dueDate: '2026-01-20',
    assignedTo: 'Jennifer Walsh',
    recordType: 'document',
    recordId: 'doc-batch-protocols',
  },
  {
    id: 'act-008',
    type: 'expiring',
    priority: 'high',
    title: 'TMF Archive Retention Expiring',
    description: 'LIG-102 TMF archive reaches 15-year retention limit',
    dueDate: '2026-02-15',
    recordType: 'study',
    recordId: 'tmf-lig-102',
  },
];

// ============================================================================
// Mock Data - Health Metrics (v0.13.75)
// ============================================================================

const MOCK_DOCUMENTS_BY_TYPE: ArchiveTypeBreakdown[] = [
  { type: 'submission', label: 'Submissions', count: 423, percentage: 14.9, color: '#3B82F6' },
  { type: 'clinical', label: 'Clinical', count: 892, percentage: 31.3, color: '#10B981' },
  { type: 'nonclinical', label: 'Nonclinical', count: 456, percentage: 16.0, color: '#F59E0B' },
  { type: 'cmc', label: 'CMC', count: 387, percentage: 13.6, color: '#8B5CF6' },
  { type: 'quality', label: 'Quality', count: 312, percentage: 11.0, color: '#EF4444' },
  { type: 'correspondence', label: 'Correspondence', count: 234, percentage: 8.2, color: '#06B6D4' },
  { type: 'other', label: 'Other', count: 143, percentage: 5.0, color: '#64748B' },
];

const MOCK_STUDIES_BY_TYPE: ArchiveTypeBreakdown[] = [
  { type: 'clinical-trial', label: 'Clinical Trials', count: 87, percentage: 55.8, color: '#10B981' },
  { type: 'glp-study', label: 'GLP Studies', count: 34, percentage: 21.8, color: '#F59E0B' },
  { type: 'bioavailability', label: 'BA/BE Studies', count: 18, percentage: 11.5, color: '#3B82F6' },
  { type: 'pk-pd', label: 'PK/PD Studies', count: 12, percentage: 7.7, color: '#8B5CF6' },
  { type: 'stability', label: 'Stability', count: 5, percentage: 3.2, color: '#EF4444' },
];

const MOCK_SPECIMENS_BY_TYPE: ArchiveTypeBreakdown[] = [
  { type: 'serum', label: 'Serum', count: 4235, percentage: 34.0, color: '#EF4444' },
  { type: 'plasma', label: 'Plasma', count: 3890, percentage: 31.2, color: '#F59E0B' },
  { type: 'tissue', label: 'Tissue', count: 1567, percentage: 12.6, color: '#8B5CF6' },
  { type: 'stability', label: 'Stability', count: 1234, percentage: 9.9, color: '#3B82F6' },
  { type: 'dna', label: 'DNA', count: 876, percentage: 7.0, color: '#10B981' },
  { type: 'retention', label: 'Retention', count: 648, percentage: 5.2, color: '#64748B' },
];

const MOCK_RECENT_ACTIVITY: RecentArchiveActivity[] = [
  {
    id: 'activity-001',
    timestamp: '2026-01-07T14:32:00Z',
    eventType: 'archive-accessed',
    recordType: 'document',
    recordId: 'doc-2847',
    recordTitle: 'LIG-401 Clinical Study Report v2.0',
    userName: 'Sarah Chen',
    description: 'Retrieved for regulatory submission review',
  },
  {
    id: 'activity-002',
    timestamp: '2026-01-07T11:15:00Z',
    eventType: 'archive-created',
    recordType: 'study',
    recordId: 'study-156',
    recordTitle: 'LIG-502 Phase II Archive Package',
    userName: 'Michael Torres',
    description: 'Study closeout archive completed',
  },
  {
    id: 'activity-003',
    timestamp: '2026-01-07T09:45:00Z',
    eventType: 'legal-hold-applied',
    recordType: 'study',
    recordId: 'study-003',
    recordTitle: 'LIG-301 All Materials',
    userName: 'Legal Department',
    description: 'Litigation hold per case #2026-LIT-001',
  },
  {
    id: 'activity-004',
    timestamp: '2026-01-06T16:20:00Z',
    eventType: 'review-completed',
    recordType: 'document',
    recordId: 'doc-1523',
    recordTitle: 'LIG-201 Stability Data Package',
    userName: 'Jennifer Walsh',
    description: 'Annual periodic review - compliant',
  },
  {
    id: 'activity-005',
    timestamp: '2026-01-06T14:00:00Z',
    eventType: 'custody-transferred',
    recordType: 'specimen',
    recordId: 'specimen-batch-445',
    recordTitle: 'LIG-301 Retention Samples (24 vials)',
    userName: 'Robert Kim',
    description: 'Transferred to cold storage facility B',
  },
  {
    id: 'activity-006',
    timestamp: '2026-01-06T10:30:00Z',
    eventType: 'retention-extended',
    recordType: 'document',
    recordId: 'doc-892',
    recordTitle: 'LIG-102 Manufacturing Batch Records',
    userName: 'Michael Torres',
    description: 'Extended 5 years per quality directive QD-2026-001',
  },
  {
    id: 'activity-007',
    timestamp: '2026-01-05T15:45:00Z',
    eventType: 'archive-destroyed',
    recordType: 'document',
    recordId: 'doc-batch-2010',
    recordTitle: 'Training Records 2010 (47 documents)',
    userName: 'Jennifer Walsh',
    description: 'Destroyed per retention schedule RS-TR-15',
  },
  {
    id: 'activity-008',
    timestamp: '2026-01-05T11:00:00Z',
    eventType: 'retrieval-completed',
    recordType: 'document',
    recordId: 'doc-445',
    recordTitle: 'FDA Type B Meeting Minutes 2023',
    userName: 'Sarah Chen',
    description: 'Delivered to Regulatory Affairs',
  },
];

const MOCK_COMPLIANCE_TREND = [
  { month: 'Aug', score: 91 },
  { month: 'Sep', score: 92 },
  { month: 'Oct', score: 93 },
  { month: 'Nov', score: 92 },
  { month: 'Dec', score: 94 },
  { month: 'Jan', score: 94 },
];

const MOCK_STORAGE_GROWTH = [
  { month: 'Aug', usedTB: 38.5 },
  { month: 'Sep', usedTB: 40.1 },
  { month: 'Oct', usedTB: 41.8 },
  { month: 'Nov', usedTB: 43.2 },
  { month: 'Dec', usedTB: 44.5 },
  { month: 'Jan', usedTB: 45.2 },
];

const MOCK_HEALTH_METRICS: ArchiveHealthMetrics = {
  documentsByType: MOCK_DOCUMENTS_BY_TYPE,
  studiesByType: MOCK_STUDIES_BY_TYPE,
  specimensByType: MOCK_SPECIMENS_BY_TYPE,
  recentActivity: MOCK_RECENT_ACTIVITY,
  complianceTrend: MOCK_COMPLIANCE_TREND,
  storageGrowth: MOCK_STORAGE_GROWTH,
};

// ============================================================================
// Mock Data - Archived Documents (v0.13.76)
// ============================================================================

const MOCK_DOCUMENTS: ArchivedDocument[] = [
  {
    id: 'doc-001',
    documentId: 'DOC-2019-CSR-001',
    title: 'LIG-201 Phase II Clinical Study Report',
    type: 'clinical',
    status: 'active',
    sourceModule: 'Document Control',
    sourceId: 'DC-4521',
    version: '2.0',
    archiveDate: '2023-06-15',
    archivedBy: 'Jennifer Walsh',
    archiveReason: 'Study closeout - final approved version',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2038-06-15',
    storageLocation: 'Archive Vault A / Shelf 12 / Box 3',
    mediaType: 'hybrid',
    fileSize: 45000000,
    lastReviewDate: '2025-06-15',
    nextReviewDate: '2026-06-15',
    reviewedBy: 'Michael Torres',
    programId: 'PRG-LIG-200',
    applicationId: 'NDA-2024-001',
    studyId: 'LIG-201',
    isElectronicallySigned: true,
    signatureDate: '2023-05-20',
    signedBy: 'Dr. Sarah Chen',
  },
  {
    id: 'doc-002',
    documentId: 'DOC-2022-NDA-001',
    title: 'LIG-401 NDA Module 2.5 Clinical Overview',
    type: 'submission',
    status: 'active',
    sourceModule: 'Authoring',
    sourceId: 'AUTH-8892',
    version: '1.0',
    archiveDate: '2024-03-10',
    archivedBy: 'Sarah Chen',
    archiveReason: 'NDA submission - regulatory archive',
    retentionPeriod: 25,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2049-03-10',
    storageLocation: 'Electronic Archive / NDA-2024-002',
    mediaType: 'electronic',
    fileSize: 12500000,
    lastReviewDate: '2025-03-10',
    nextReviewDate: '2026-03-10',
    reviewedBy: 'Jennifer Walsh',
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    isElectronicallySigned: true,
    signatureDate: '2024-03-05',
    signedBy: 'Dr. Robert Kim',
  },
  {
    id: 'doc-003',
    documentId: 'DOC-2021-TOX-001',
    title: 'LIG-301 26-Week Carcinogenicity Study Report',
    type: 'nonclinical',
    status: 'legal-hold',
    sourceModule: 'GLP Compliance',
    sourceId: 'GLP-2234',
    version: '1.0',
    archiveDate: '2022-09-20',
    archivedBy: 'Robert Kim',
    archiveReason: 'GLP study completion - final report',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2037-09-20',
    storageLocation: 'Archive Vault B / Shelf 5 / Box 8',
    mediaType: 'hybrid',
    fileSize: 89000000,
    programId: 'PRG-LIG-300',
    studyId: 'GLP-LIG-301-CARC',
    isElectronicallySigned: true,
    signatureDate: '2022-09-15',
    signedBy: 'Dr. Lisa Park',
  },
  {
    id: 'doc-004',
    documentId: 'DOC-2023-CMC-001',
    title: 'LIG-401 Drug Substance Specification',
    type: 'cmc',
    status: 'active',
    sourceModule: 'CMC & Manufacturing',
    sourceId: 'CMC-5567',
    version: '3.0',
    archiveDate: '2024-01-15',
    archivedBy: 'Michael Torres',
    archiveReason: 'Superseded - new version approved',
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2034-01-15',
    storageLocation: 'Electronic Archive / CMC-Archives',
    mediaType: 'electronic',
    fileSize: 5600000,
    lastReviewDate: '2025-01-15',
    nextReviewDate: '2026-01-15',
    reviewedBy: 'Sarah Chen',
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    isElectronicallySigned: true,
    signatureDate: '2024-01-10',
    signedBy: 'Dr. James Wilson',
  },
  {
    id: 'doc-005',
    documentId: 'DOC-2020-DEV-001',
    title: 'SOP-QA-001 Deviation Management',
    type: 'quality',
    status: 'pending-review',
    sourceModule: 'QMS',
    sourceId: 'QMS-1123',
    version: '4.0',
    archiveDate: '2023-12-01',
    archivedBy: 'Jennifer Walsh',
    archiveReason: 'Superseded by version 5.0',
    retentionPeriod: 7,
    retentionBasis: 'company-policy',
    retentionExpiryDate: '2030-12-01',
    storageLocation: 'Electronic Archive / QMS-SOPs',
    mediaType: 'electronic',
    fileSize: 890000,
    nextReviewDate: '2025-12-01',
    isElectronicallySigned: true,
    signatureDate: '2023-11-28',
    signedBy: 'Quality Director',
  },
  {
    id: 'doc-006',
    documentId: 'DOC-2024-HAQ-001',
    title: 'FDA Day 74 Response - Clinical Questions',
    type: 'correspondence',
    status: 'active',
    sourceModule: 'HAQ Intelligence',
    sourceId: 'HAQ-7789',
    version: '1.0',
    archiveDate: '2025-02-15',
    archivedBy: 'Sarah Chen',
    archiveReason: 'HAQ response submitted and acknowledged',
    retentionPeriod: 25,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2050-02-15',
    storageLocation: 'Electronic Archive / HAQ-Responses',
    mediaType: 'electronic',
    fileSize: 23000000,
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    isElectronicallySigned: true,
    signatureDate: '2025-02-10',
    signedBy: 'Dr. Sarah Chen',
  },
  {
    id: 'doc-007',
    documentId: 'DOC-2019-PROT-001',
    title: 'LIG-201 Phase II Protocol v3.0',
    type: 'clinical',
    status: 'active',
    sourceModule: 'Study Design',
    sourceId: 'SD-3345',
    version: '3.0',
    archiveDate: '2021-08-30',
    archivedBy: 'Robert Kim',
    archiveReason: 'Study complete - protocol archive',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2036-08-30',
    storageLocation: 'Archive Vault A / Shelf 8 / Box 1',
    mediaType: 'hybrid',
    fileSize: 8900000,
    lastReviewDate: '2024-08-30',
    nextReviewDate: '2025-08-30',
    reviewedBy: 'Jennifer Walsh',
    programId: 'PRG-LIG-200',
    studyId: 'LIG-201',
    isElectronicallySigned: true,
    signatureDate: '2021-08-25',
    signedBy: 'Dr. Michael Chen',
  },
  {
    id: 'doc-008',
    documentId: 'DOC-2023-STAB-001',
    title: 'LIG-401 36-Month Stability Report',
    type: 'cmc',
    status: 'active',
    sourceModule: 'CMC & Manufacturing',
    sourceId: 'CMC-6678',
    version: '1.0',
    archiveDate: '2025-01-05',
    archivedBy: 'Michael Torres',
    archiveReason: 'Stability study complete - final report',
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2035-01-05',
    storageLocation: 'Electronic Archive / Stability-Data',
    mediaType: 'electronic',
    fileSize: 34000000,
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    isElectronicallySigned: true,
    signatureDate: '2025-01-02',
    signedBy: 'Stability Manager',
  },
  {
    id: 'doc-009',
    documentId: 'DOC-2022-IB-001',
    title: 'LIG-301 Investigator Brochure v5.0',
    type: 'clinical',
    status: 'legal-hold',
    sourceModule: 'Document Control',
    sourceId: 'DC-5567',
    version: '5.0',
    archiveDate: '2024-06-20',
    archivedBy: 'Jennifer Walsh',
    archiveReason: 'Superseded by v6.0',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2039-06-20',
    storageLocation: 'Archive Vault B / Shelf 3 / Box 2',
    mediaType: 'hybrid',
    fileSize: 15600000,
    programId: 'PRG-LIG-300',
    studyId: 'LIG-301',
    isElectronicallySigned: true,
    signatureDate: '2024-06-15',
    signedBy: 'Medical Director',
  },
  {
    id: 'doc-010',
    documentId: 'DOC-2010-TRAIN-001',
    title: 'GCP Training Records 2010 - Batch Archive',
    type: 'quality',
    status: 'pending-destruction',
    sourceModule: 'QMS',
    sourceId: 'QMS-0445',
    version: '1.0',
    archiveDate: '2011-01-15',
    archivedBy: 'HR Training',
    archiveReason: 'Annual training records archive',
    retentionPeriod: 15,
    retentionBasis: 'company-policy',
    retentionExpiryDate: '2026-01-15',
    storageLocation: 'Archive Vault C / Shelf 1 / Box 47',
    mediaType: 'physical',
    isElectronicallySigned: false,
  },
  {
    id: 'doc-011',
    documentId: 'DOC-2024-LABEL-001',
    title: 'LIG-401 US Package Insert - Approved',
    type: 'labeling',
    status: 'active',
    sourceModule: 'Labeling',
    sourceId: 'LBL-2234',
    version: '1.0',
    archiveDate: '2025-11-15',
    archivedBy: 'Sarah Chen',
    archiveReason: 'FDA approved labeling - regulatory archive',
    retentionPeriod: 25,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2050-11-15',
    storageLocation: 'Electronic Archive / Approved-Labels',
    mediaType: 'electronic',
    fileSize: 4500000,
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    isElectronicallySigned: true,
    signatureDate: '2025-11-10',
    signedBy: 'Regulatory Director',
  },
  {
    id: 'doc-012',
    documentId: 'DOC-2018-PKPD-001',
    title: 'LIG-101 Population PK Analysis Report',
    type: 'nonclinical',
    status: 'retrieved',
    sourceModule: 'Clinical Pharmacology',
    sourceId: 'CP-1123',
    version: '1.0',
    archiveDate: '2019-03-20',
    archivedBy: 'Robert Kim',
    archiveReason: 'Phase I complete - final PK report',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2034-03-20',
    storageLocation: 'Archive Vault A / Shelf 2 / Box 5',
    mediaType: 'hybrid',
    fileSize: 67000000,
    lastReviewDate: '2024-03-20',
    nextReviewDate: '2025-03-20',
    reviewedBy: 'Michael Torres',
    programId: 'PRG-LIG-100',
    studyId: 'LIG-101',
    isElectronicallySigned: true,
    signatureDate: '2019-03-15',
    signedBy: 'Clinical Pharmacologist',
  },
];

// ============================================================================
// Mock Data - Archived Studies (v0.13.77)
// ============================================================================

const MOCK_STUDIES: ArchivedStudy[] = [
  {
    id: 'study-001',
    studyId: 'LIG-201',
    title: 'A Phase II, Randomized, Double-Blind Study of LIG-201 in Moderate-to-Severe Rheumatoid Arthritis',
    type: 'clinical-trial',
    status: 'archived',
    phase: 'Phase II',
    indication: 'Rheumatoid Arthritis',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2023-08-15',
    closeoutDate: '2023-06-30',
    archivedBy: 'Jennifer Walsh',
    dataVolume: '2.3 TB',
    recordCount: 15420,
    subjectCount: 342,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2038-08-15',
    storageLocation: 'Electronic Archive / Clinical-Studies / LIG-201',
    mediaType: 'electronic',
    programId: 'PRG-LIG-200',
    applicationId: 'NDA-2024-001',
    linkedDocuments: ['doc-001', 'doc-007'],
    tmfArchiveId: 'TMF-LIG-201',
    ctmsStudyId: 'CTMS-201',
  },
  {
    id: 'study-002',
    studyId: 'LIG-301',
    title: 'A Phase III, Multicenter Study of LIG-301 in Patients with Advanced Solid Tumors',
    type: 'clinical-trial',
    status: 'legal-hold',
    phase: 'Phase III',
    indication: 'Solid Tumors (Oncology)',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2024-02-28',
    closeoutDate: '2024-01-15',
    archivedBy: 'Michael Torres',
    dataVolume: '4.8 TB',
    recordCount: 34560,
    subjectCount: 892,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2039-02-28',
    storageLocation: 'Electronic Archive / Clinical-Studies / LIG-301',
    mediaType: 'electronic',
    programId: 'PRG-LIG-300',
    linkedDocuments: ['doc-003', 'doc-009'],
    tmfArchiveId: 'TMF-LIG-301',
    ctmsStudyId: 'CTMS-301',
  },
  {
    id: 'study-003',
    studyId: 'GLP-LIG-301-CARC',
    title: 'LIG-301 26-Week Carcinogenicity Study in CD-1 Mice',
    type: 'glp-study',
    status: 'archived',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2022-11-30',
    closeoutDate: '2022-09-15',
    archivedBy: 'Robert Kim',
    dataVolume: '890 GB',
    recordCount: 8934,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2037-11-30',
    storageLocation: 'Archive Vault B / GLP Studies / Box 12-18',
    mediaType: 'hybrid',
    programId: 'PRG-LIG-300',
    linkedDocuments: ['doc-003'],
    glpStudyId: 'GLP-2022-CARC-001',
  },
  {
    id: 'study-004',
    studyId: 'LIG-401-BE-001',
    title: 'Bioequivalence Study of LIG-401 Tablet Formulations Under Fasted Conditions',
    type: 'bioavailability',
    status: 'archived',
    phase: 'Phase I',
    indication: 'Bioequivalence',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2024-06-20',
    closeoutDate: '2024-05-01',
    archivedBy: 'Sarah Chen',
    dataVolume: '125 GB',
    recordCount: 2340,
    subjectCount: 48,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2039-06-20',
    storageLocation: 'Electronic Archive / BA-BE-Studies / LIG-401-BE',
    mediaType: 'electronic',
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    linkedDocuments: [],
    ctmsStudyId: 'CTMS-401-BE',
  },
  {
    id: 'study-005',
    studyId: 'LIG-101-PK',
    title: 'Population Pharmacokinetic Analysis of LIG-101 in Healthy Volunteers',
    type: 'pk-pd',
    status: 'archived',
    phase: 'Phase I',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2019-12-15',
    closeoutDate: '2019-10-30',
    archivedBy: 'Robert Kim',
    dataVolume: '340 GB',
    recordCount: 4560,
    subjectCount: 124,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2034-12-15',
    storageLocation: 'Electronic Archive / PK-Studies / LIG-101',
    mediaType: 'electronic',
    programId: 'PRG-LIG-100',
    linkedDocuments: ['doc-012'],
    ctmsStudyId: 'CTMS-101',
  },
  {
    id: 'study-006',
    studyId: 'LIG-401-STAB-36M',
    title: 'LIG-401 Drug Product 36-Month Stability Study (25°C/60% RH)',
    type: 'stability',
    status: 'archived',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2025-01-10',
    closeoutDate: '2024-12-20',
    archivedBy: 'Michael Torres',
    dataVolume: '45 GB',
    recordCount: 1230,
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2035-01-10',
    storageLocation: 'Electronic Archive / Stability-Studies / LIG-401',
    mediaType: 'electronic',
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    linkedDocuments: ['doc-008'],
  },
  {
    id: 'study-007',
    studyId: 'GLP-LIG-201-TOX-28D',
    title: 'LIG-201 28-Day Repeat-Dose Toxicity Study in Sprague-Dawley Rats',
    type: 'glp-study',
    status: 'archived',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2020-03-15',
    closeoutDate: '2020-01-30',
    archivedBy: 'Jennifer Walsh',
    dataVolume: '560 GB',
    recordCount: 6780,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2035-03-15',
    storageLocation: 'Archive Vault A / GLP Studies / Box 5-8',
    mediaType: 'hybrid',
    programId: 'PRG-LIG-200',
    linkedDocuments: [],
    glpStudyId: 'GLP-2019-TOX-001',
  },
  {
    id: 'study-008',
    studyId: 'LIG-102',
    title: 'A Phase I, First-in-Human, Dose-Escalation Study of LIG-102 in Healthy Adults',
    type: 'clinical-trial',
    status: 'pending-closeout',
    phase: 'Phase I',
    indication: 'First-in-Human',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2025-12-01',
    closeoutDate: '2025-10-15',
    archivedBy: 'Sarah Chen',
    dataVolume: '780 GB',
    recordCount: 5670,
    subjectCount: 64,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2040-12-01',
    storageLocation: 'Electronic Archive / Clinical-Studies / LIG-102',
    mediaType: 'electronic',
    programId: 'PRG-LIG-100',
    linkedDocuments: [],
    tmfArchiveId: 'TMF-LIG-102',
    ctmsStudyId: 'CTMS-102',
  },
  {
    id: 'study-009',
    studyId: 'LIG-401-DDI',
    title: 'Drug-Drug Interaction Study of LIG-401 with CYP3A4 Inhibitors',
    type: 'pk-pd',
    status: 'retrieved',
    phase: 'Phase I',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2024-08-30',
    closeoutDate: '2024-07-15',
    archivedBy: 'Robert Kim',
    dataVolume: '180 GB',
    recordCount: 2890,
    subjectCount: 36,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2039-08-30',
    storageLocation: 'Electronic Archive / PK-Studies / LIG-401-DDI',
    mediaType: 'electronic',
    programId: 'PRG-LIG-400',
    applicationId: 'NDA-2024-002',
    linkedDocuments: [],
    ctmsStudyId: 'CTMS-401-DDI',
  },
  {
    id: 'study-010',
    studyId: 'LIG-501-OBS',
    title: 'Post-Marketing Observational Study of LIG-501 in Real-World Clinical Practice',
    type: 'observational',
    status: 'partial',
    indication: 'Post-Marketing Surveillance',
    sponsor: 'Ligature Therapeutics',
    archiveDate: '2025-06-15',
    closeoutDate: '2025-04-30',
    archivedBy: 'Jennifer Walsh',
    dataVolume: '1.2 TB',
    recordCount: 12340,
    subjectCount: 2450,
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    retentionExpiryDate: '2040-06-15',
    storageLocation: 'Electronic Archive / Observational / LIG-501',
    mediaType: 'electronic',
    programId: 'PRG-LIG-500',
    linkedDocuments: [],
  },
];

// ============================================================================
// Mock Data - Specimens (v0.13.78)
// ============================================================================

const MOCK_SPECIMENS: Specimen[] = [
  {
    id: 'spec-001',
    sampleId: 'BIO-LIG201-001-V1',
    type: 'serum',
    status: 'stored',
    studyId: 'LIG-201',
    subjectId: 'SUBJ-001',
    visitId: 'V1-Baseline',
    collectionDate: '2023-03-15',
    storageLocation: 'Biobank A / Freezer F-02 / Rack 3 / Box 12 / Position A1',
    storageCondition: 'frozen-80',
    containerType: '2mL Cryovial',
    volume: 1.5,
    aliquotCount: 3,
    expiryDate: '2033-03-15',
    lastAccessDate: '2025-06-20',
    accessCount: 2,
    custodyHistory: [
      { id: 'cust-001', timestamp: '2023-03-15T10:30:00Z', fromCustodian: 'Clinical Site 001', toCustodian: 'Central Lab', reason: 'Initial collection', witnessedBy: 'J. Smith' },
      { id: 'cust-002', timestamp: '2023-03-20T14:00:00Z', fromCustodian: 'Central Lab', toCustodian: 'Biobank A', reason: 'Long-term storage', witnessedBy: 'M. Chen' },
    ],
    currentCustodian: 'Biobank A',
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-002',
    sampleId: 'BIO-LIG201-002-V3',
    type: 'plasma',
    status: 'stored',
    studyId: 'LIG-201',
    subjectId: 'SUBJ-002',
    visitId: 'V3-Week4',
    collectionDate: '2023-04-20',
    storageLocation: 'Biobank A / Freezer F-02 / Rack 3 / Box 12 / Position B2',
    storageCondition: 'frozen-80',
    containerType: '2mL Cryovial',
    volume: 2.0,
    aliquotCount: 4,
    expiryDate: '2033-04-20',
    lastAccessDate: '2024-11-15',
    accessCount: 1,
    custodyHistory: [
      { id: 'cust-003', timestamp: '2023-04-20T09:00:00Z', fromCustodian: 'Clinical Site 002', toCustodian: 'Central Lab', reason: 'Initial collection', witnessedBy: 'R. Kim' },
      { id: 'cust-004', timestamp: '2023-04-25T11:30:00Z', fromCustodian: 'Central Lab', toCustodian: 'Biobank A', reason: 'Long-term storage', witnessedBy: 'M. Chen' },
    ],
    currentCustodian: 'Biobank A',
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-003',
    sampleId: 'STAB-LIG401-T24',
    type: 'stability',
    status: 'stored',
    studyId: 'LIG-401-STAB',
    collectionDate: '2024-01-15',
    storageLocation: 'Stability Chamber SC-01 / Shelf 2 / Position 14',
    storageCondition: 'controlled-humidity',
    containerType: '100mL HDPE Bottle',
    volume: 85,
    expiryDate: '2027-01-15',
    lastAccessDate: '2025-12-01',
    accessCount: 12,
    custodyHistory: [
      { id: 'cust-005', timestamp: '2024-01-15T08:00:00Z', fromCustodian: 'Manufacturing', toCustodian: 'Stability Lab', reason: 'Stability study initiation', witnessedBy: 'T. Walsh' },
    ],
    currentCustodian: 'Stability Lab',
    retentionPeriod: 5,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 1,
  },
  {
    id: 'spec-004',
    sampleId: 'DNA-LIG301-045',
    type: 'dna',
    status: 'stored',
    studyId: 'LIG-301',
    subjectId: 'SUBJ-045',
    visitId: 'V1-Screening',
    collectionDate: '2022-08-10',
    storageLocation: 'Biobank B / LN2 Tank T-03 / Rack 1 / Box 5 / Position C3',
    storageCondition: 'liquid-nitrogen',
    containerType: '1mL Matrix Tube',
    volume: 0.5,
    aliquotCount: 2,
    expiryDate: '2042-08-10',
    lastAccessDate: '2024-02-20',
    accessCount: 3,
    custodyHistory: [
      { id: 'cust-006', timestamp: '2022-08-10T11:00:00Z', fromCustodian: 'Clinical Site 003', toCustodian: 'Genomics Lab', reason: 'DNA extraction', witnessedBy: 'P. Johnson' },
      { id: 'cust-007', timestamp: '2022-08-20T15:00:00Z', fromCustodian: 'Genomics Lab', toCustodian: 'Biobank B', reason: 'Long-term cryo storage', witnessedBy: 'S. Lee' },
    ],
    currentCustodian: 'Biobank B',
    retentionPeriod: 20,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-005',
    sampleId: 'TISSUE-LIG301-012',
    type: 'tissue',
    status: 'stored',
    studyId: 'LIG-301',
    subjectId: 'SUBJ-012',
    visitId: 'Biopsy-W8',
    collectionDate: '2022-10-05',
    storageLocation: 'Pathology Archive / FFPE Block PA-2022-0456',
    storageCondition: 'ambient',
    containerType: 'FFPE Block',
    expiryDate: '2037-10-05',
    lastAccessDate: '2023-05-15',
    accessCount: 4,
    custodyHistory: [
      { id: 'cust-008', timestamp: '2022-10-05T14:30:00Z', fromCustodian: 'Clinical Site 001', toCustodian: 'Pathology Lab', reason: 'Tissue processing', witnessedBy: 'D. Martinez' },
      { id: 'cust-009', timestamp: '2022-10-15T09:00:00Z', fromCustodian: 'Pathology Lab', toCustodian: 'Pathology Archive', reason: 'FFPE block storage', witnessedBy: 'K. Thompson' },
    ],
    currentCustodian: 'Pathology Archive',
    retentionPeriod: 15,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-006',
    sampleId: 'RET-LIG401-BATCH-001',
    type: 'retention',
    status: 'stored',
    studyId: 'LIG-401-MFG',
    collectionDate: '2024-06-01',
    storageLocation: 'QC Retention Archive / Cabinet RC-02 / Shelf 3',
    storageCondition: 'refrigerated',
    containerType: '50mL Glass Vial',
    volume: 45,
    expiryDate: '2029-06-01',
    lastAccessDate: '2025-01-05',
    accessCount: 2,
    custodyHistory: [
      { id: 'cust-010', timestamp: '2024-06-01T16:00:00Z', fromCustodian: 'Manufacturing QC', toCustodian: 'Retention Archive', reason: 'Batch retention sample', witnessedBy: 'A. Wilson' },
    ],
    currentCustodian: 'Retention Archive',
    retentionPeriod: 5,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-007',
    sampleId: 'CSF-LIG201-008-V2',
    type: 'csf',
    status: 'depleted',
    studyId: 'LIG-201',
    subjectId: 'SUBJ-008',
    visitId: 'V2-Week2',
    collectionDate: '2023-04-01',
    storageLocation: 'Biobank A / Freezer F-01 / Rack 1 / Box 3 / Position D4',
    storageCondition: 'frozen-80',
    containerType: '0.5mL Cryovial',
    volume: 0,
    aliquotCount: 0,
    expiryDate: '2033-04-01',
    lastAccessDate: '2025-09-10',
    accessCount: 5,
    custodyHistory: [
      { id: 'cust-011', timestamp: '2023-04-01T10:00:00Z', fromCustodian: 'Clinical Site 001', toCustodian: 'Central Lab', reason: 'Initial collection', witnessedBy: 'N. Garcia' },
      { id: 'cust-012', timestamp: '2023-04-05T13:00:00Z', fromCustodian: 'Central Lab', toCustodian: 'Biobank A', reason: 'Long-term storage', witnessedBy: 'M. Chen' },
    ],
    currentCustodian: 'Biobank A',
    retentionPeriod: 10,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-008',
    sampleId: 'URINE-LIG102-023-V4',
    type: 'urine',
    status: 'stored',
    studyId: 'LIG-102',
    subjectId: 'SUBJ-023',
    visitId: 'V4-Week8',
    collectionDate: '2025-08-15',
    storageLocation: 'Biobank A / Freezer F-03 / Rack 2 / Box 8 / Position E5',
    storageCondition: 'frozen-20',
    containerType: '10mL Conical Tube',
    volume: 8.5,
    aliquotCount: 2,
    expiryDate: '2030-08-15',
    lastAccessDate: '2025-11-01',
    accessCount: 1,
    custodyHistory: [
      { id: 'cust-013', timestamp: '2025-08-15T07:30:00Z', fromCustodian: 'Clinical Site 004', toCustodian: 'Central Lab', reason: 'Initial collection', witnessedBy: 'L. Brown' },
      { id: 'cust-014', timestamp: '2025-08-18T10:00:00Z', fromCustodian: 'Central Lab', toCustodian: 'Biobank A', reason: 'Long-term storage', witnessedBy: 'M. Chen' },
    ],
    currentCustodian: 'Biobank A',
    retentionPeriod: 5,
    retentionBasis: 'regulatory',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-009',
    sampleId: 'REF-STD-001',
    type: 'reference',
    status: 'in-use',
    collectionDate: '2024-03-01',
    storageLocation: 'QC Lab / Reference Standards Cabinet / Position RS-15',
    storageCondition: 'refrigerated',
    containerType: '25mg Amber Glass Vial',
    volume: 18,
    expiryDate: '2026-03-01',
    lastAccessDate: '2026-01-06',
    accessCount: 24,
    custodyHistory: [
      { id: 'cust-015', timestamp: '2024-03-01T09:00:00Z', fromCustodian: 'Vendor (Sigma-Aldrich)', toCustodian: 'QC Lab', reason: 'Reference standard receipt', witnessedBy: 'J. Anderson' },
    ],
    currentCustodian: 'QC Lab',
    retentionPeriod: 2,
    retentionBasis: 'company-policy',
    qualityStatus: 'acceptable',
    temperatureExcursions: 0,
  },
  {
    id: 'spec-010',
    sampleId: 'PLASMA-LIG301-099-V1',
    type: 'plasma',
    status: 'expired',
    studyId: 'LIG-301',
    subjectId: 'SUBJ-099',
    visitId: 'V1-Baseline',
    collectionDate: '2020-02-10',
    storageLocation: 'Biobank A / Freezer F-02 / Rack 4 / Box 1 / Position F6',
    storageCondition: 'frozen-80',
    containerType: '2mL Cryovial',
    volume: 1.8,
    aliquotCount: 3,
    expiryDate: '2025-02-10',
    lastAccessDate: '2024-06-20',
    accessCount: 2,
    custodyHistory: [
      { id: 'cust-016', timestamp: '2020-02-10T11:30:00Z', fromCustodian: 'Clinical Site 002', toCustodian: 'Central Lab', reason: 'Initial collection', witnessedBy: 'C. Davis' },
      { id: 'cust-017', timestamp: '2020-02-15T14:00:00Z', fromCustodian: 'Central Lab', toCustodian: 'Biobank A', reason: 'Long-term storage', witnessedBy: 'M. Chen' },
    ],
    currentCustodian: 'Biobank A',
    retentionPeriod: 5,
    retentionBasis: 'regulatory',
    qualityStatus: 'compromised',
    temperatureExcursions: 2,
  },
];

// ============================================================================
// Mock Data - Retention Schedules (v0.13.79)
// ============================================================================

const MOCK_SCHEDULES: RetentionSchedule[] = [
  {
    id: 'sched-001',
    recordType: 'clinical-data',
    name: 'Clinical Trial Data (ICH E6)',
    description: 'Clinical trial essential documents, CRFs, source data, and study databases per ICH E6(R2) GCP guidelines',
    retentionPeriod: 15,
    basis: 'regulatory',
    regulatoryReference: 'ICH E6(R2) Section 4.9.5',
    region: 'Global',
    applicableDocTypes: ['clinical', 'submission'],
    recordsCount: 892,
    autoDestructionEnabled: false,
    reviewReminderDays: 365,
    createdDate: '2020-01-15',
    lastModified: '2025-06-01',
    modifiedBy: 'Jennifer Walsh',
  },
  {
    id: 'sched-002',
    recordType: 'nonclinical-data',
    name: 'GLP Study Archives (21 CFR 58)',
    description: 'Nonclinical laboratory study raw data, specimens, protocols, and final reports per FDA GLP regulations',
    retentionPeriod: 15,
    basis: 'regulatory',
    regulatoryReference: '21 CFR Part 58.195',
    region: 'US',
    jurisdiction: 'FDA',
    applicableDocTypes: ['nonclinical'],
    recordsCount: 456,
    autoDestructionEnabled: false,
    reviewReminderDays: 365,
    createdDate: '2019-03-10',
    lastModified: '2024-12-15',
    modifiedBy: 'Robert Kim',
  },
  {
    id: 'sched-003',
    recordType: 'regulatory-filing',
    name: 'Regulatory Submissions (eCTD)',
    description: 'NDA, BLA, MAA submissions and amendments, including all eCTD sequences and correspondence',
    retentionPeriod: 25,
    basis: 'regulatory',
    regulatoryReference: '21 CFR 314.81',
    region: 'Global',
    applicableDocTypes: ['submission', 'regulatory', 'correspondence'],
    recordsCount: 423,
    autoDestructionEnabled: false,
    reviewReminderDays: 730,
    createdDate: '2018-06-20',
    lastModified: '2025-11-30',
    modifiedBy: 'Sarah Chen',
  },
  {
    id: 'sched-004',
    recordType: 'adverse-events',
    name: 'Pharmacovigilance Records (EU GVP)',
    description: 'ICSRs, PSURs, DSURs, signal detection records, and safety database per EU GVP Module VI',
    retentionPeriod: 10,
    basis: 'regulatory',
    regulatoryReference: 'EU GVP Module VI.C.3',
    region: 'EU',
    jurisdiction: 'EMA',
    applicableDocTypes: ['safety'],
    recordsCount: 312,
    autoDestructionEnabled: true,
    reviewReminderDays: 180,
    createdDate: '2021-02-28',
    lastModified: '2025-09-15',
    modifiedBy: 'Michael Torres',
  },
  {
    id: 'sched-005',
    recordType: 'batch-records',
    name: 'Manufacturing Batch Records',
    description: 'Production batch records, in-process controls, release testing, and deviation records',
    retentionPeriod: 7,
    basis: 'regulatory',
    regulatoryReference: '21 CFR 211.180',
    region: 'US',
    jurisdiction: 'FDA',
    applicableDocTypes: ['cmc', 'quality'],
    recordsCount: 387,
    autoDestructionEnabled: true,
    reviewReminderDays: 90,
    createdDate: '2020-08-15',
    lastModified: '2025-10-20',
    modifiedBy: 'Michael Torres',
  },
  {
    id: 'sched-006',
    recordType: 'stability-data',
    name: 'Stability Study Data',
    description: 'Drug product and drug substance stability studies, including accelerated and long-term data',
    retentionPeriod: 10,
    basis: 'regulatory',
    regulatoryReference: 'ICH Q1A(R2)',
    region: 'Global',
    applicableDocTypes: ['cmc', 'nonclinical'],
    recordsCount: 234,
    autoDestructionEnabled: false,
    reviewReminderDays: 365,
    createdDate: '2019-11-01',
    lastModified: '2025-08-10',
    modifiedBy: 'Robert Kim',
  },
  {
    id: 'sched-007',
    recordType: 'quality-records',
    name: 'QMS Documentation',
    description: 'SOPs, change controls, CAPAs, deviations, complaints, and quality agreements',
    retentionPeriod: 10,
    basis: 'regulatory',
    regulatoryReference: '21 CFR 820.180',
    region: 'US',
    jurisdiction: 'FDA',
    applicableDocTypes: ['quality'],
    recordsCount: 567,
    autoDestructionEnabled: true,
    reviewReminderDays: 180,
    createdDate: '2018-04-01',
    lastModified: '2025-12-01',
    modifiedBy: 'Jennifer Walsh',
  },
  {
    id: 'sched-008',
    recordType: 'training-records',
    name: 'Personnel Training Records',
    description: 'Employee training documentation, competency assessments, and qualification records',
    retentionPeriod: 7,
    basis: 'company-policy',
    regulatoryReference: '21 CFR 211.25',
    region: 'Global',
    applicableDocTypes: ['quality', 'other'],
    recordsCount: 1245,
    autoDestructionEnabled: true,
    reviewReminderDays: 30,
    createdDate: '2017-01-15',
    lastModified: '2025-11-15',
    modifiedBy: 'Jennifer Walsh',
  },
  {
    id: 'sched-009',
    recordType: 'correspondence',
    name: 'Health Authority Correspondence',
    description: 'FDA, EMA, PMDA, and other HA meeting minutes, official correspondence, and commitments',
    retentionPeriod: 25,
    basis: 'regulatory',
    regulatoryReference: '21 CFR 314.81(b)(2)',
    region: 'Global',
    applicableDocTypes: ['correspondence', 'regulatory'],
    recordsCount: 189,
    autoDestructionEnabled: false,
    reviewReminderDays: 730,
    createdDate: '2018-09-01',
    lastModified: '2025-07-20',
    modifiedBy: 'Sarah Chen',
  },
  {
    id: 'sched-010',
    recordType: 'audit-records',
    name: 'Audit & Inspection Records',
    description: 'Internal audits, external inspections, 483 responses, warning letters, and corrective actions',
    retentionPeriod: 15,
    basis: 'regulatory',
    regulatoryReference: '21 CFR 820.22',
    region: 'Global',
    applicableDocTypes: ['quality', 'regulatory'],
    recordsCount: 156,
    autoDestructionEnabled: false,
    reviewReminderDays: 365,
    createdDate: '2019-05-10',
    lastModified: '2025-10-05',
    modifiedBy: 'Robert Kim',
  },
];

// ============================================================================
// Mock Data - Audit Entries (v0.13.80)
// ============================================================================

const MOCK_AUDIT_ENTRIES: ArchiveAuditEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-01-07T14:32:15Z',
    eventType: 'archive-accessed',
    recordType: 'document',
    recordId: 'doc-2847',
    recordTitle: 'LIG-401 Clinical Study Report v2.0',
    userId: 'user-chen',
    userName: 'Sarah Chen',
    userRole: 'Regulatory Affairs Director',
    description: 'Retrieved document for regulatory submission review',
    reason: 'NDA preparation',
    ipAddress: '10.0.1.45',
    electronicSignature: false,
  },
  {
    id: 'audit-002',
    timestamp: '2026-01-07T11:15:30Z',
    eventType: 'archive-created',
    recordType: 'study',
    recordId: 'study-156',
    recordTitle: 'LIG-502 Phase II Archive Package',
    userId: 'user-torres',
    userName: 'Michael Torres',
    userRole: 'Clinical Operations Manager',
    description: 'Study closeout archive package created',
    reason: 'Study completion per protocol',
    ipAddress: '10.0.1.23',
    electronicSignature: true,
    signatureId: 'SIG-2026-0147',
  },
  {
    id: 'audit-003',
    timestamp: '2026-01-07T09:45:00Z',
    eventType: 'legal-hold-applied',
    recordType: 'study',
    recordId: 'study-003',
    recordTitle: 'LIG-301 All Materials',
    userId: 'user-legal',
    userName: 'Legal Department',
    userRole: 'Legal Counsel',
    description: 'Litigation hold applied to all LIG-301 study materials',
    reason: 'Pending litigation - Case #2026-LIT-001',
    ipAddress: '10.0.2.10',
    electronicSignature: true,
    signatureId: 'SIG-2026-0145',
  },
  {
    id: 'audit-004',
    timestamp: '2026-01-06T16:20:45Z',
    eventType: 'review-completed',
    recordType: 'document',
    recordId: 'doc-1523',
    recordTitle: 'LIG-201 Stability Data Package',
    userId: 'user-walsh',
    userName: 'Jennifer Walsh',
    userRole: 'Quality Assurance Manager',
    description: 'Annual periodic review completed - archive compliant',
    ipAddress: '10.0.1.67',
    electronicSignature: true,
    signatureId: 'SIG-2026-0142',
  },
  {
    id: 'audit-005',
    timestamp: '2026-01-06T14:00:22Z',
    eventType: 'custody-transferred',
    recordType: 'specimen',
    recordId: 'specimen-batch-445',
    recordTitle: 'LIG-301 Retention Samples (24 vials)',
    userId: 'user-kim',
    userName: 'Robert Kim',
    userRole: 'Biobank Supervisor',
    description: 'Chain of custody transfer to cold storage facility B',
    previousValue: 'Biobank A / Freezer F-02',
    newValue: 'Cold Storage B / LN2 Tank T-05',
    reason: 'Capacity optimization',
    ipAddress: '10.0.3.15',
    electronicSignature: true,
    signatureId: 'SIG-2026-0140',
  },
  {
    id: 'audit-006',
    timestamp: '2026-01-06T10:30:15Z',
    eventType: 'retention-extended',
    recordType: 'document',
    recordId: 'doc-892',
    recordTitle: 'LIG-102 Manufacturing Batch Records',
    userId: 'user-torres',
    userName: 'Michael Torres',
    userRole: 'Clinical Operations Manager',
    description: 'Retention period extended per quality directive',
    previousValue: '7 years',
    newValue: '12 years',
    reason: 'Quality Directive QD-2026-001',
    ipAddress: '10.0.1.23',
    electronicSignature: true,
    signatureId: 'SIG-2026-0138',
  },
  {
    id: 'audit-007',
    timestamp: '2026-01-05T15:45:30Z',
    eventType: 'archive-destroyed',
    recordType: 'document',
    recordId: 'doc-batch-2010',
    recordTitle: 'Training Records 2010 (47 documents)',
    userId: 'user-walsh',
    userName: 'Jennifer Walsh',
    userRole: 'Quality Assurance Manager',
    description: 'Batch destruction completed per retention schedule RS-TR-15',
    reason: 'Retention period expired - 15 years complete',
    ipAddress: '10.0.1.67',
    electronicSignature: true,
    signatureId: 'SIG-2026-0135',
  },
  {
    id: 'audit-008',
    timestamp: '2026-01-05T11:20:00Z',
    eventType: 'retrieval-requested',
    recordType: 'document',
    recordId: 'doc-015',
    recordTitle: 'FDA Pre-NDA Meeting Package (2023)',
    userId: 'user-chen',
    userName: 'Sarah Chen',
    userRole: 'Regulatory Affairs Director',
    description: 'Access request submitted for regulatory review',
    reason: 'NDA submission preparation',
    ipAddress: '10.0.1.45',
    electronicSignature: false,
  },
  {
    id: 'audit-009',
    timestamp: '2026-01-05T09:15:45Z',
    eventType: 'archive-modified',
    recordType: 'schedule',
    recordId: 'sched-004',
    recordTitle: 'Pharmacovigilance Records (EU GVP)',
    userId: 'user-torres',
    userName: 'Michael Torres',
    userRole: 'Clinical Operations Manager',
    description: 'Updated review reminder period',
    previousValue: '90 days',
    newValue: '180 days',
    reason: 'Alignment with EU GVP Module VI update',
    ipAddress: '10.0.1.23',
    electronicSignature: true,
    signatureId: 'SIG-2026-0130',
  },
  {
    id: 'audit-010',
    timestamp: '2026-01-04T16:40:20Z',
    eventType: 'retrieval-completed',
    recordType: 'document',
    recordId: 'doc-789',
    recordTitle: 'LIG-201 Protocol Amendment 3',
    userId: 'user-kim',
    userName: 'Robert Kim',
    userRole: 'Biobank Supervisor',
    description: 'Document retrieved and delivered to requestor',
    reason: 'Protocol reference for new study',
    ipAddress: '10.0.3.15',
    electronicSignature: false,
  },
  {
    id: 'audit-011',
    timestamp: '2026-01-04T14:25:10Z',
    eventType: 'legal-hold-released',
    recordType: 'study',
    recordId: 'study-098',
    recordTitle: 'LIG-105 Phase I Materials',
    userId: 'user-legal',
    userName: 'Legal Department',
    userRole: 'Legal Counsel',
    description: 'Litigation hold released - case settled',
    reason: 'Case #2024-LIT-015 resolved',
    ipAddress: '10.0.2.10',
    electronicSignature: true,
    signatureId: 'SIG-2026-0128',
  },
  {
    id: 'audit-012',
    timestamp: '2026-01-04T10:10:55Z',
    eventType: 'archive-accessed',
    recordType: 'specimen',
    recordId: 'spec-003',
    recordTitle: 'STAB-LIG401-T24 Stability Sample',
    userId: 'user-kim',
    userName: 'Robert Kim',
    userRole: 'Biobank Supervisor',
    description: 'Sample accessed for 24-month stability testing',
    reason: 'Scheduled stability timepoint',
    ipAddress: '10.0.3.15',
    electronicSignature: false,
  },
  {
    id: 'audit-013',
    timestamp: '2026-01-03T15:55:30Z',
    eventType: 'archive-created',
    recordType: 'document',
    recordId: 'doc-2848',
    recordTitle: 'LIG-401 CMC Module 3.2.P.8 Stability',
    userId: 'user-chen',
    userName: 'Sarah Chen',
    userRole: 'Regulatory Affairs Director',
    description: 'New CMC stability document archived',
    reason: 'NDA Module 3 preparation',
    ipAddress: '10.0.1.45',
    electronicSignature: true,
    signatureId: 'SIG-2026-0125',
  },
  {
    id: 'audit-014',
    timestamp: '2026-01-03T11:30:00Z',
    eventType: 'custody-transferred',
    recordType: 'document',
    recordId: 'doc-batch-glp',
    recordTitle: 'GLP Raw Data Binders (12 volumes)',
    userId: 'user-walsh',
    userName: 'Jennifer Walsh',
    userRole: 'Quality Assurance Manager',
    description: 'Physical records transferred to offsite archive',
    previousValue: 'On-site Archive Room A',
    newValue: 'Iron Mountain Vault #4521',
    reason: 'Space optimization - physical records offsite storage',
    ipAddress: '10.0.1.67',
    electronicSignature: true,
    signatureId: 'SIG-2026-0122',
  },
  {
    id: 'audit-015',
    timestamp: '2026-01-02T09:00:15Z',
    eventType: 'review-completed',
    recordType: 'study',
    recordId: 'study-045',
    recordTitle: 'LIG-201 Phase II RA Study Archive',
    userId: 'user-walsh',
    userName: 'Jennifer Walsh',
    userRole: 'Quality Assurance Manager',
    description: 'Quarterly archive review completed - no issues found',
    ipAddress: '10.0.1.67',
    electronicSignature: true,
    signatureId: 'SIG-2026-0118',
  },
];

// ============================================================================
// Initial State
// ============================================================================

const initialState: ArchivesState = {
  // UI State
  activeTab: 'dashboard',
  filters: {},
  isLoading: false,
  error: null,
  
  // Data
  documents: MOCK_DOCUMENTS,
  studies: MOCK_STUDIES,
  specimens: MOCK_SPECIMENS,
  schedules: MOCK_SCHEDULES,
  auditEntries: MOCK_AUDIT_ENTRIES,
  
  // Dashboard
  metrics: MOCK_METRICS,
  actionItems: MOCK_ACTION_ITEMS,
  healthMetrics: MOCK_HEALTH_METRICS,
  
  // Selection
  selectedDocumentId: null,
  selectedStudyId: null,
  selectedSpecimenId: null,
};

// ============================================================================
// Store Definition
// ============================================================================

export const useArchivesStore = create<ArchivesState & ArchivesActions>((set, get) => ({
  ...initialState,
  
  // Tab navigation
  setActiveTab: (tab: ArchiveTab) => set({ activeTab: tab }),
  
  // Filters
  setFilters: (filters: Partial<ArchiveFilters>) => 
    set(state => ({ filters: { ...state.filters, ...filters } })),
  
  clearFilters: () => set({ filters: {} }),
  
  // Selection
  selectDocument: (id: string | null) => set({ selectedDocumentId: id }),
  selectStudy: (id: string | null) => set({ selectedStudyId: id }),
  selectSpecimen: (id: string | null) => set({ selectedSpecimenId: id }),
  
  // Data operations
  refreshData: async () => {
    set({ isLoading: true, error: null });
    try {
      // Future: API calls to refresh data
      await new Promise(resolve => setTimeout(resolve, 500));
      set({ isLoading: false });
    } catch (error) {
      set({ isLoading: false, error: 'Failed to refresh archive data' });
    }
  },
}));

// ============================================================================
// Selector Hooks
// ============================================================================

export const useArchiveTab = () => useArchivesStore(state => state.activeTab);
export const useArchiveFilters = () => useArchivesStore(state => state.filters);
export const useArchiveMetrics = () => useArchivesStore(state => state.metrics);
export const useArchiveActionItems = () => useArchivesStore(state => state.actionItems);
export const useArchiveHealthMetrics = () => useArchivesStore(state => state.healthMetrics);
export const useArchiveDocuments = () => useArchivesStore(state => state.documents);
export const useArchiveStudies = () => useArchivesStore(state => state.studies);
export const useArchiveSpecimens = () => useArchivesStore(state => state.specimens);
export const useArchiveSchedules = () => useArchivesStore(state => state.schedules);
export const useArchiveAuditEntries = () => useArchivesStore(state => state.auditEntries);
export const useArchiveLoading = () => useArchivesStore(state => state.isLoading);
export const useArchiveError = () => useArchivesStore(state => state.error);

// Selected items
export const useSelectedDocument = () => useArchivesStore(state => 
  state.documents.find(d => d.id === state.selectedDocumentId) || null
);
export const useSelectedStudy = () => useArchivesStore(state => 
  state.studies.find(s => s.id === state.selectedStudyId) || null
);
export const useSelectedSpecimen = () => useArchivesStore(state => 
  state.specimens.find(s => s.id === state.selectedSpecimenId) || null
);
