

// ============================================================================
// Document Link Store - v172: Cross-Module Document Linking Infrastructure
// ============================================================================
// Centralized, indexed store for managing millions of document links across
// TMF, eCTD, Safety, HAQ, QMS, and other modules. Designed for O(1) lookups
// with bidirectional traversal, batch operations, and lazy loading.
// ============================================================================

import { create } from 'zustand';
import { useShallow } from 'zustand/react/shallow';

// ============================================================================
// LINK TYPES & ENUMS
// ============================================================================

export type LinkableModule = 
  | 'tmf'           // Trial Master File artifacts
  | 'ectd'          // eCTD sequences and leaves
  | 'safety'        // ICSR cases, signals
  | 'haq'           // HAQ responses
  | 'qms'           // QMS deviations, CAPAs
  | 'ctms'          // Clinical trial events
  | 'authoring'     // Document authoring
  | 'publishing';   // Publishing sequences

export type LinkType =
  // TMF ↔ eCTD
  | 'tmf-to-ectd'           // TMF artifact sourced to eCTD sequence
  | 'ectd-to-tmf'           // eCTD document filed to TMF
  
  // Safety ↔ Clinical
  | 'safety-to-clinical'    // Safety signal linked to trial data
  | 'clinical-to-safety'    // Clinical AE linked to safety case
  
  // HAQ ↔ Source Documents
  | 'haq-to-source'         // HAQ response cites source document
  | 'source-to-haq'         // Document referenced by HAQ
  
  // QMS ↔ Trial Events
  | 'qms-to-trial'          // QMS deviation linked to trial event
  | 'trial-to-qms'          // Trial event triggered QMS action
  
  // General purpose
  | 'reference'             // Generic reference link
  | 'supersedes'            // Version supersession
  | 'derives-from'          // Derived content
  | 'supports';             // Supporting evidence

export type LinkStatus = 'active' | 'pending' | 'broken' | 'archived';

export type LinkDirection = 'forward' | 'reverse' | 'bidirectional';

// ============================================================================
// LINK STRUCTURE
// ============================================================================

export interface DocumentLink {
  id: string;
  
  // Source document
  sourceModule: LinkableModule;
  sourceId: string;
  sourceType: string;          // e.g., 'tmf-artifact', 'ectd-leaf', 'icsr-case'
  sourceTitle: string;
  sourceVersion?: string;
  
  // Target document
  targetModule: LinkableModule;
  targetId: string;
  targetType: string;
  targetTitle: string;
  targetVersion?: string;
  
  // Link metadata
  linkType: LinkType;
  direction: LinkDirection;
  status: LinkStatus;
  strength: 'strong' | 'weak' | 'inferred';  // How certain is this link
  
  // Context
  context?: LinkContext;
  
  // Audit
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  lastValidatedAt?: string;
  autoGenerated: boolean;
  
  // Optional metadata
  metadata?: Record<string, unknown>;
}

export interface LinkContext {
  // Where in the source document
  sourceSection?: string;
  sourcePageRange?: [number, number];
  
  // Where in the target document  
  targetSection?: string;
  targetPageRange?: [number, number];
  
  // Relationship description
  description?: string;
  
  // Tags for filtering
  tags?: string[];
}

// ============================================================================
// LINK QUERY & FILTER
// ============================================================================

export interface LinkQuery {
  // Filter by module
  sourceModule?: LinkableModule | LinkableModule[];
  targetModule?: LinkableModule | LinkableModule[];
  
  // Filter by ID
  sourceId?: string;
  targetId?: string;
  
  // Filter by type
  linkType?: LinkType | LinkType[];
  sourceType?: string;
  targetType?: string;
  
  // Filter by status
  status?: LinkStatus | LinkStatus[];
  
  // Filter by strength
  strength?: 'strong' | 'weak' | 'inferred';
  
  // Filter by date range
  createdAfter?: string;
  createdBefore?: string;
  
  // Text search
  searchText?: string;
  
  // Pagination
  limit?: number;
  offset?: number;
}

export interface LinkQueryResult {
  links: DocumentLink[];
  total: number;
  hasMore: boolean;
  offset: number;
}

// ============================================================================
// BATCH OPERATIONS
// ============================================================================

export interface BatchLinkOperation {
  type: 'create' | 'update' | 'delete' | 'archive';
  links: Partial<DocumentLink>[];
}

export interface BatchLinkResult {
  success: number;
  failed: number;
  errors: { index: number; error: string }[];
}

// ============================================================================
// LINK STATISTICS
// ============================================================================

export interface LinkStatistics {
  totalLinks: number;
  linksByModule: Record<LinkableModule, number>;
  linksByType: Record<LinkType, number>;
  linksByStatus: Record<LinkStatus, number>;
  brokenLinks: number;
  recentlyCreated: number; // Last 24 hours
  autoGeneratedPercentage: number;
}

// ============================================================================
// STORE STATE
// ============================================================================

interface DocumentLinkState {
  // Primary storage - links by ID
  links: Record<string, DocumentLink>;
  
  // Forward index: source -> link IDs
  // Key format: `${sourceModule}:${sourceId}`
  sourceIndex: Record<string, Set<string>>;
  
  // Reverse index: target -> link IDs
  // Key format: `${targetModule}:${targetId}`
  targetIndex: Record<string, Set<string>>;
  
  // Type index for fast filtering
  typeIndex: Record<LinkType, Set<string>>;
  
  // Module pair index for cross-module queries
  // Key format: `${sourceModule}:${targetModule}`
  modulePairIndex: Record<string, Set<string>>;
  
  // Loading state
  isLoading: boolean;
  lastError: string | null;
  
  // Statistics cache
  statisticsCache: LinkStatistics | null;
  statisticsCacheTime: string | null;
}

interface DocumentLinkActions {
  // CRUD operations
  createLink: (link: Omit<DocumentLink, 'id' | 'createdAt' | 'updatedAt'>) => DocumentLink;
  updateLink: (linkId: string, updates: Partial<DocumentLink>) => void;
  deleteLink: (linkId: string) => void;
  archiveLink: (linkId: string) => void;
  
  // Batch operations
  createLinks: (links: Omit<DocumentLink, 'id' | 'createdAt' | 'updatedAt'>[]) => BatchLinkResult;
  deleteLinks: (linkIds: string[]) => BatchLinkResult;
  archiveLinks: (linkIds: string[]) => BatchLinkResult;
  
  // Query operations (O(1) indexed lookups)
  getLinkById: (linkId: string) => DocumentLink | null;
  getLinksFromSource: (module: LinkableModule, sourceId: string) => DocumentLink[];
  getLinksToTarget: (module: LinkableModule, targetId: string) => DocumentLink[];
  getBidirectionalLinks: (module: LinkableModule, documentId: string) => DocumentLink[];
  getLinksBetweenModules: (sourceModule: LinkableModule, targetModule: LinkableModule) => DocumentLink[];
  
  // Advanced queries with filtering
  queryLinks: (query: LinkQuery) => LinkQueryResult;
  
  // Link validation
  validateLink: (linkId: string) => { valid: boolean; issues: string[] };
  validateAllLinks: () => { total: number; broken: number; issues: string[] };
  repairBrokenLinks: () => number;
  
  // Statistics
  getStatistics: () => LinkStatistics;
  refreshStatistics: () => LinkStatistics;
  
  // Convenience methods for specific module pairs
  linkTMFToECTD: (tmfArtifactId: string, ectdLeafId: string, metadata?: Record<string, unknown>) => DocumentLink;
  linkSafetyToClinical: (safetyId: string, clinicalEventId: string, metadata?: Record<string, unknown>) => DocumentLink;
  linkHAQToSource: (haqId: string, sourceDocId: string, sourceModule: LinkableModule, metadata?: Record<string, unknown>) => DocumentLink;
  linkQMSToTrial: (qmsId: string, trialEventId: string, metadata?: Record<string, unknown>) => DocumentLink;
  
  // Bulk import/export
  exportLinks: (query?: LinkQuery) => DocumentLink[];
  importLinks: (links: DocumentLink[]) => BatchLinkResult;
  
  // Store management
  clearAllLinks: () => void;
  loadMockData: () => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

const generateLinkId = () => `link-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

const getSourceKey = (module: LinkableModule, id: string) => `${module}:${id}`;
const getTargetKey = (module: LinkableModule, id: string) => `${module}:${id}`;
const getModulePairKey = (source: LinkableModule, target: LinkableModule) => `${source}:${target}`;

// ============================================================================
// STORE IMPLEMENTATION
// ============================================================================

export const useDocumentLinkStore = create<DocumentLinkState & DocumentLinkActions>((set, get) => ({
  // Initial state
  links: {},
  sourceIndex: {},
  targetIndex: {},
  typeIndex: {
    'tmf-to-ectd': new Set(),
    'ectd-to-tmf': new Set(),
    'safety-to-clinical': new Set(),
    'clinical-to-safety': new Set(),
    'haq-to-source': new Set(),
    'source-to-haq': new Set(),
    'qms-to-trial': new Set(),
    'trial-to-qms': new Set(),
    'reference': new Set(),
    'supersedes': new Set(),
    'derives-from': new Set(),
    'supports': new Set(),
  },
  modulePairIndex: {},
  isLoading: false,
  lastError: null,
  statisticsCache: null,
  statisticsCacheTime: null,

  // CRUD: Create
  createLink: (linkData) => {
    const id = generateLinkId();
    const now = new Date().toISOString();
    
    const link: DocumentLink = {
      ...linkData,
      id,
      createdAt: now,
      updatedAt: now,
    };
    
    set((state) => {
      // Add to primary storage
      const newLinks = { ...state.links, [id]: link };
      
      // Update source index
      const sourceKey = getSourceKey(link.sourceModule, link.sourceId);
      const newSourceIndex = { ...state.sourceIndex };
      if (!newSourceIndex[sourceKey]) {
        newSourceIndex[sourceKey] = new Set();
      }
      newSourceIndex[sourceKey] = new Set(Array.from(newSourceIndex[sourceKey]).concat([id]));
      
      // Update target index
      const targetKey = getTargetKey(link.targetModule, link.targetId);
      const newTargetIndex = { ...state.targetIndex };
      if (!newTargetIndex[targetKey]) {
        newTargetIndex[targetKey] = new Set();
      }
      newTargetIndex[targetKey] = new Set(Array.from(newTargetIndex[targetKey]).concat([id]));
      
      // Update type index
      const newTypeIndex = { ...state.typeIndex };
      newTypeIndex[link.linkType] = new Set(Array.from(newTypeIndex[link.linkType]).concat([id]));
      
      // Update module pair index
      const pairKey = getModulePairKey(link.sourceModule, link.targetModule);
      const newModulePairIndex = { ...state.modulePairIndex };
      if (!newModulePairIndex[pairKey]) {
        newModulePairIndex[pairKey] = new Set();
      }
      newModulePairIndex[pairKey] = new Set(Array.from(newModulePairIndex[pairKey]).concat([id]));
      
      return {
        links: newLinks,
        sourceIndex: newSourceIndex,
        targetIndex: newTargetIndex,
        typeIndex: newTypeIndex,
        modulePairIndex: newModulePairIndex,
        statisticsCache: null, // Invalidate cache
      };
    });
    
    return get().links[id];
  },

  // CRUD: Update
  updateLink: (linkId, updates) => {
    const link = get().links[linkId];
    if (!link) return;
    
    set((state) => ({
      links: {
        ...state.links,
        [linkId]: {
          ...link,
          ...updates,
          updatedAt: new Date().toISOString(),
        },
      },
      statisticsCache: null,
    }));
  },

  // CRUD: Delete
  deleteLink: (linkId) => {
    const link = get().links[linkId];
    if (!link) return;
    
    set((state) => {
      // Remove from primary storage
      const { [linkId]: _, ...remainingLinks } = state.links;
      
      // Remove from source index
      const sourceKey = getSourceKey(link.sourceModule, link.sourceId);
      const newSourceIndex = { ...state.sourceIndex };
      if (newSourceIndex[sourceKey]) {
        const newSet = new Set(newSourceIndex[sourceKey]);
        newSet.delete(linkId);
        newSourceIndex[sourceKey] = newSet;
      }
      
      // Remove from target index
      const targetKey = getTargetKey(link.targetModule, link.targetId);
      const newTargetIndex = { ...state.targetIndex };
      if (newTargetIndex[targetKey]) {
        const newSet = new Set(newTargetIndex[targetKey]);
        newSet.delete(linkId);
        newTargetIndex[targetKey] = newSet;
      }
      
      // Remove from type index
      const newTypeIndex = { ...state.typeIndex };
      const typeSet = new Set(newTypeIndex[link.linkType]);
      typeSet.delete(linkId);
      newTypeIndex[link.linkType] = typeSet;
      
      // Remove from module pair index
      const pairKey = getModulePairKey(link.sourceModule, link.targetModule);
      const newModulePairIndex = { ...state.modulePairIndex };
      if (newModulePairIndex[pairKey]) {
        const newSet = new Set(newModulePairIndex[pairKey]);
        newSet.delete(linkId);
        newModulePairIndex[pairKey] = newSet;
      }
      
      return {
        links: remainingLinks,
        sourceIndex: newSourceIndex,
        targetIndex: newTargetIndex,
        typeIndex: newTypeIndex,
        modulePairIndex: newModulePairIndex,
        statisticsCache: null,
      };
    });
  },

  // CRUD: Archive
  archiveLink: (linkId) => {
    get().updateLink(linkId, { status: 'archived' });
  },

  // Batch: Create
  createLinks: (linksData) => {
    const results: BatchLinkResult = { success: 0, failed: 0, errors: [] };
    
    linksData.forEach((linkData, index) => {
      try {
        get().createLink(linkData);
        results.success++;
      } catch (error) {
        results.failed++;
        results.errors.push({ index, error: String(error) });
      }
    });
    
    return results;
  },

  // Batch: Delete
  deleteLinks: (linkIds) => {
    const results: BatchLinkResult = { success: 0, failed: 0, errors: [] };
    
    linkIds.forEach((linkId, index) => {
      try {
        if (get().links[linkId]) {
          get().deleteLink(linkId);
          results.success++;
        } else {
          results.failed++;
          results.errors.push({ index, error: 'Link not found' });
        }
      } catch (error) {
        results.failed++;
        results.errors.push({ index, error: String(error) });
      }
    });
    
    return results;
  },

  // Batch: Archive
  archiveLinks: (linkIds) => {
    const results: BatchLinkResult = { success: 0, failed: 0, errors: [] };
    
    linkIds.forEach((linkId, index) => {
      try {
        if (get().links[linkId]) {
          get().archiveLink(linkId);
          results.success++;
        } else {
          results.failed++;
          results.errors.push({ index, error: 'Link not found' });
        }
      } catch (error) {
        results.failed++;
        results.errors.push({ index, error: String(error) });
      }
    });
    
    return results;
  },

  // Query: By ID (O(1))
  getLinkById: (linkId) => {
    return get().links[linkId] || null;
  },

  // Query: From source (O(1) index lookup + O(n) for n links)
  getLinksFromSource: (module, sourceId) => {
    const sourceKey = getSourceKey(module, sourceId);
    const linkIds = get().sourceIndex[sourceKey];
    if (!linkIds) return [];
    
    return Array.from(linkIds)
      .map(id => get().links[id])
      .filter(Boolean);
  },

  // Query: To target (O(1) index lookup + O(n) for n links)
  getLinksToTarget: (module, targetId) => {
    const targetKey = getTargetKey(module, targetId);
    const linkIds = get().targetIndex[targetKey];
    if (!linkIds) return [];
    
    return Array.from(linkIds)
      .map(id => get().links[id])
      .filter(Boolean);
  },

  // Query: Bidirectional (combines source and target)
  getBidirectionalLinks: (module, documentId) => {
    const fromSource = get().getLinksFromSource(module, documentId);
    const toTarget = get().getLinksToTarget(module, documentId);
    
    // Deduplicate by link ID
    const seenIds = new Set<string>();
    const result: DocumentLink[] = [];
    
    [...fromSource, ...toTarget].forEach(link => {
      if (!seenIds.has(link.id)) {
        seenIds.add(link.id);
        result.push(link);
      }
    });
    
    return result;
  },

  // Query: Between modules (O(1) index lookup)
  getLinksBetweenModules: (sourceModule, targetModule) => {
    const pairKey = getModulePairKey(sourceModule, targetModule);
    const linkIds = get().modulePairIndex[pairKey];
    if (!linkIds) return [];
    
    return Array.from(linkIds)
      .map(id => get().links[id])
      .filter(Boolean);
  },

  // Advanced query with filtering
  queryLinks: (query) => {
    let linkIds: Set<string> | null = null;
    const state = get();
    
    // Start with the most selective index
    if (query.sourceId && query.sourceModule) {
      const key = getSourceKey(
        Array.isArray(query.sourceModule) ? query.sourceModule[0] : query.sourceModule,
        query.sourceId
      );
      linkIds = state.sourceIndex[key] || new Set();
    } else if (query.targetId && query.targetModule) {
      const key = getTargetKey(
        Array.isArray(query.targetModule) ? query.targetModule[0] : query.targetModule,
        query.targetId
      );
      linkIds = state.targetIndex[key] || new Set();
    } else if (query.linkType && !Array.isArray(query.linkType)) {
      linkIds = state.typeIndex[query.linkType] || new Set();
    } else {
      // Full scan
      linkIds = new Set(Object.keys(state.links));
    }
    
    // Apply filters
    let results = Array.from(linkIds)
      .map(id => state.links[id])
      .filter(Boolean)
      .filter(link => {
        // Source module filter
        if (query.sourceModule) {
          const modules = Array.isArray(query.sourceModule) ? query.sourceModule : [query.sourceModule];
          if (!modules.includes(link.sourceModule)) return false;
        }
        
        // Target module filter
        if (query.targetModule) {
          const modules = Array.isArray(query.targetModule) ? query.targetModule : [query.targetModule];
          if (!modules.includes(link.targetModule)) return false;
        }
        
        // Link type filter
        if (query.linkType) {
          const types = Array.isArray(query.linkType) ? query.linkType : [query.linkType];
          if (!types.includes(link.linkType)) return false;
        }
        
        // Status filter
        if (query.status) {
          const statuses = Array.isArray(query.status) ? query.status : [query.status];
          if (!statuses.includes(link.status)) return false;
        }
        
        // Strength filter
        if (query.strength && link.strength !== query.strength) return false;
        
        // Date filters
        if (query.createdAfter && link.createdAt < query.createdAfter) return false;
        if (query.createdBefore && link.createdAt > query.createdBefore) return false;
        
        // Text search
        if (query.searchText) {
          const search = query.searchText.toLowerCase();
          if (!link.sourceTitle.toLowerCase().includes(search) &&
              !link.targetTitle.toLowerCase().includes(search)) {
            return false;
          }
        }
        
        return true;
      });
    
    const total = results.length;
    const offset = query.offset || 0;
    const limit = query.limit || 100;
    
    results = results.slice(offset, offset + limit);
    
    return {
      links: results,
      total,
      hasMore: offset + results.length < total,
      offset,
    };
  },

  // Link validation
  validateLink: (linkId) => {
    const link = get().links[linkId];
    if (!link) return { valid: false, issues: ['Link not found'] };
    
    const issues: string[] = [];
    
    // Check required fields
    if (!link.sourceId) issues.push('Missing source ID');
    if (!link.targetId) issues.push('Missing target ID');
    if (!link.sourceTitle) issues.push('Missing source title');
    if (!link.targetTitle) issues.push('Missing target title');
    
    // TODO: In production, validate that source and target documents exist
    
    return {
      valid: issues.length === 0,
      issues,
    };
  },

  validateAllLinks: () => {
    const links = Object.values(get().links);
    let broken = 0;
    const issues: string[] = [];
    
    links.forEach(link => {
      const validation = get().validateLink(link.id);
      if (!validation.valid) {
        broken++;
        issues.push(`${link.id}: ${validation.issues.join(', ')}`);
      }
    });
    
    return { total: links.length, broken, issues };
  },

  repairBrokenLinks: () => {
    // Mark broken links as 'broken' status
    const links = Object.values(get().links);
    let repaired = 0;
    
    links.forEach(link => {
      const validation = get().validateLink(link.id);
      if (!validation.valid && link.status !== 'broken') {
        get().updateLink(link.id, { status: 'broken' });
        repaired++;
      }
    });
    
    return repaired;
  },

  // Statistics
  getStatistics: () => {
    const state = get();
    
    // Return cached if fresh (< 5 minutes old)
    if (state.statisticsCache && state.statisticsCacheTime) {
      const cacheAge = Date.now() - new Date(state.statisticsCacheTime).getTime();
      if (cacheAge < 5 * 60 * 1000) {
        return state.statisticsCache;
      }
    }
    
    return get().refreshStatistics();
  },

  refreshStatistics: () => {
    const links = Object.values(get().links);
    const now = new Date();
    const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString();
    
    const stats: LinkStatistics = {
      totalLinks: links.length,
      linksByModule: {
        tmf: 0, ectd: 0, safety: 0, haq: 0, qms: 0, ctms: 0, authoring: 0, publishing: 0,
      },
      linksByType: {
        'tmf-to-ectd': 0, 'ectd-to-tmf': 0, 'safety-to-clinical': 0, 'clinical-to-safety': 0,
        'haq-to-source': 0, 'source-to-haq': 0, 'qms-to-trial': 0, 'trial-to-qms': 0,
        'reference': 0, 'supersedes': 0, 'derives-from': 0, 'supports': 0,
      },
      linksByStatus: { active: 0, pending: 0, broken: 0, archived: 0 },
      brokenLinks: 0,
      recentlyCreated: 0,
      autoGeneratedPercentage: 0,
    };
    
    let autoGenerated = 0;
    
    links.forEach(link => {
      stats.linksByModule[link.sourceModule]++;
      stats.linksByType[link.linkType]++;
      stats.linksByStatus[link.status]++;
      
      if (link.status === 'broken') stats.brokenLinks++;
      if (link.createdAt >= oneDayAgo) stats.recentlyCreated++;
      if (link.autoGenerated) autoGenerated++;
    });
    
    stats.autoGeneratedPercentage = links.length > 0 
      ? Math.round((autoGenerated / links.length) * 100) 
      : 0;
    
    set({
      statisticsCache: stats,
      statisticsCacheTime: now.toISOString(),
    });
    
    return stats;
  },

  // Convenience: TMF to eCTD
  linkTMFToECTD: (tmfArtifactId, ectdLeafId, metadata) => {
    return get().createLink({
      sourceModule: 'tmf',
      sourceId: tmfArtifactId,
      sourceType: 'tmf-artifact',
      sourceTitle: `TMF Artifact ${tmfArtifactId}`,
      targetModule: 'ectd',
      targetId: ectdLeafId,
      targetType: 'ectd-leaf',
      targetTitle: `eCTD Leaf ${ectdLeafId}`,
      linkType: 'tmf-to-ectd',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: false,
      metadata,
    });
  },

  // Convenience: Safety to Clinical
  linkSafetyToClinical: (safetyId, clinicalEventId, metadata) => {
    return get().createLink({
      sourceModule: 'safety',
      sourceId: safetyId,
      sourceType: 'icsr-case',
      sourceTitle: `Safety Case ${safetyId}`,
      targetModule: 'ctms',
      targetId: clinicalEventId,
      targetType: 'clinical-event',
      targetTitle: `Clinical Event ${clinicalEventId}`,
      linkType: 'safety-to-clinical',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: false,
      metadata,
    });
  },

  // Convenience: HAQ to Source
  linkHAQToSource: (haqId, sourceDocId, sourceModule, metadata) => {
    return get().createLink({
      sourceModule: 'haq',
      sourceId: haqId,
      sourceType: 'haq-response',
      sourceTitle: `HAQ Response ${haqId}`,
      targetModule: sourceModule,
      targetId: sourceDocId,
      targetType: 'source-document',
      targetTitle: `Source Document ${sourceDocId}`,
      linkType: 'haq-to-source',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: false,
      metadata,
    });
  },

  // Convenience: QMS to Trial
  linkQMSToTrial: (qmsId, trialEventId, metadata) => {
    return get().createLink({
      sourceModule: 'qms',
      sourceId: qmsId,
      sourceType: 'qms-deviation',
      sourceTitle: `QMS Deviation ${qmsId}`,
      targetModule: 'ctms',
      targetId: trialEventId,
      targetType: 'trial-event',
      targetTitle: `Trial Event ${trialEventId}`,
      linkType: 'qms-to-trial',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: false,
      metadata,
    });
  },

  // Export
  exportLinks: (query) => {
    if (query) {
      return get().queryLinks({ ...query, limit: 1000000 }).links;
    }
    return Object.values(get().links);
  },

  // Import
  importLinks: (links) => {
    const results: BatchLinkResult = { success: 0, failed: 0, errors: [] };
    
    links.forEach((link, index) => {
      try {
        // Recreate with new timestamps
        get().createLink({
          ...link,
          createdBy: link.createdBy || 'import',
          autoGenerated: link.autoGenerated ?? false,
        });
        results.success++;
      } catch (error) {
        results.failed++;
        results.errors.push({ index, error: String(error) });
      }
    });
    
    return results;
  },

  // Store management
  clearAllLinks: () => {
    set({
      links: {},
      sourceIndex: {},
      targetIndex: {},
      typeIndex: {
        'tmf-to-ectd': new Set(),
        'ectd-to-tmf': new Set(),
        'safety-to-clinical': new Set(),
        'clinical-to-safety': new Set(),
        'haq-to-source': new Set(),
        'source-to-haq': new Set(),
        'qms-to-trial': new Set(),
        'trial-to-qms': new Set(),
        'reference': new Set(),
        'supersedes': new Set(),
        'derives-from': new Set(),
        'supports': new Set(),
      },
      modulePairIndex: {},
      statisticsCache: null,
      statisticsCacheTime: null,
    });
  },

  loadMockData: () => {
    const store = get();
    
    // TMF → eCTD links
    store.createLink({
      sourceModule: 'tmf',
      sourceId: 'art-02.01.01-001',
      sourceType: 'tmf-artifact',
      sourceTitle: 'Protocol v2.0',
      sourceVersion: '2.0',
      targetModule: 'ectd',
      targetId: 'leaf-m5-531-protocol',
      targetType: 'ectd-leaf',
      targetTitle: 'Module 5.3.1 Protocol',
      linkType: 'tmf-to-ectd',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: true,
    });
    
    store.createLink({
      sourceModule: 'tmf',
      sourceId: 'art-02.02.01-001',
      sourceType: 'tmf-artifact',
      sourceTitle: 'Investigator Brochure v5.0',
      sourceVersion: '5.0',
      targetModule: 'ectd',
      targetId: 'leaf-m5-531-ib',
      targetType: 'ectd-leaf',
      targetTitle: 'Module 5.3.1 Investigator Brochure',
      linkType: 'tmf-to-ectd',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: true,
    });
    
    // Safety → Clinical links
    store.createLink({
      sourceModule: 'safety',
      sourceId: 'icsr-2024-001',
      sourceType: 'icsr-case',
      sourceTitle: 'SAE Case #2024-001 - Severe Headache',
      targetModule: 'ctms',
      targetId: 'ae-event-123',
      targetType: 'adverse-event',
      targetTitle: 'AE #123 - Subject 1001, Visit 4',
      linkType: 'safety-to-clinical',
      direction: 'bidirectional',
      status: 'active',
      strength: 'strong',
      createdBy: 'sarah.chen',
      autoGenerated: false,
      context: {
        description: 'SAE case originated from clinical trial AE report',
        tags: ['serious', 'expedited'],
      },
    });
    
    // HAQ → Source links
    store.createLink({
      sourceModule: 'haq',
      sourceId: 'haq-fda-2024-q12',
      sourceType: 'haq-response',
      sourceTitle: 'FDA HAQ Q12 - CMC Manufacturing Process',
      targetModule: 'authoring',
      targetId: 'doc-cmc-process-001',
      targetType: 'source-document',
      targetTitle: 'Manufacturing Process Description v3.0',
      linkType: 'haq-to-source',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'james.wilson',
      autoGenerated: false,
      context: {
        sourceSection: 'Response Section 2.1',
        targetSection: 'Section 3.2.P.3',
        description: 'CMC response references manufacturing process document',
      },
    });
    
    // QMS → Trial links
    store.createLink({
      sourceModule: 'qms',
      sourceId: 'dev-2024-0045',
      sourceType: 'deviation',
      sourceTitle: 'DEV-2024-0045: Temperature Excursion',
      targetModule: 'ctms',
      targetId: 'site-event-456',
      targetType: 'site-event',
      targetTitle: 'Site 102 - IP Storage Issue',
      linkType: 'qms-to-trial',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'quality.team',
      autoGenerated: true,
      context: {
        description: 'Deviation triggered by site IP temperature excursion',
        tags: ['ip-related', 'resolved'],
      },
    });
    
    // Add some more variety
    store.createLink({
      sourceModule: 'ectd',
      sourceId: 'seq-0004-leaf-m1',
      sourceType: 'ectd-leaf',
      sourceTitle: 'Sequence 0004 - HAQ Response Letter',
      targetModule: 'tmf',
      targetId: 'art-03.01-haq-response',
      targetType: 'tmf-artifact',
      targetTitle: 'HAQ Response Correspondence',
      linkType: 'ectd-to-tmf',
      direction: 'forward',
      status: 'active',
      strength: 'strong',
      createdBy: 'system',
      autoGenerated: true,
    });
  },

  setLoading: (loading) => set({ isLoading: loading }),
  setError: (error) => set({ lastError: error }),
}));

// ============================================================================
// CONVENIENCE HOOKS
// ============================================================================

export const useLinksFromDocument = (module: LinkableModule, documentId: string) => {
  return useDocumentLinkStore(useShallow(state => state.getLinksFromSource(module, documentId)));
};

export const useLinksToDocument = (module: LinkableModule, documentId: string) => {
  return useDocumentLinkStore(useShallow(state => state.getLinksToTarget(module, documentId)));
};

export const useAllDocumentLinks = (module: LinkableModule, documentId: string) => {
  return useDocumentLinkStore(useShallow(state => state.getBidirectionalLinks(module, documentId)));
};

export const useLinkStatistics = () => {
  return useDocumentLinkStore(useShallow(state => state.getStatistics()));
};

export const useLinksBetweenModules = (source: LinkableModule, target: LinkableModule) => {
  return useDocumentLinkStore(useShallow(state => state.getLinksBetweenModules(source, target)));
};
