
/**
 * Supabase Configuration
 * Environment variables and type definitions
 * 
 * @version 0.27.58
 */

// =============================================================================
// ENVIRONMENT VARIABLES
// =============================================================================

export const supabaseConfig = {
  url: import.meta.env.VITE_SUPABASE_URL || '',
  anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY || '',
  serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
};

// =============================================================================
// VALIDATION
// =============================================================================

export function isSupabaseConfigured(): boolean {
  return !!(supabaseConfig.url && supabaseConfig.anonKey);
}

export function validateSupabaseConfig(): { valid: boolean; missing: string[] } {
  const missing: string[] = [];
  
  if (!supabaseConfig.url) {
    missing.push('NEXT_PUBLIC_SUPABASE_URL');
  }
  if (!supabaseConfig.anonKey) {
    missing.push('NEXT_PUBLIC_SUPABASE_ANON_KEY');
  }
  
  return {
    valid: missing.length === 0,
    missing,
  };
}

// =============================================================================
// DATABASE TYPES
// =============================================================================

// These will be auto-generated by Supabase CLI, but we define core types here
// for initial development

export type UserRole = 
  | 'ADMIN'
  | 'REGULATORY_AFFAIRS'
  | 'MEDICAL_WRITER'
  | 'QA'
  | 'CLINICAL'
  | 'CMC'
  | 'SAFETY'
  | 'USER';

export interface DbUser {
  id: string;
  email: string;
  name: string | null;
  role: UserRole;
  department: string | null;
  title: string | null;
  is_active: boolean;
  organization_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbHAQ {
  id: string;
  haq_number: string;
  application_id: string | null;
  product_id: string | null;
  question: string;
  question_type: string;
  status: string;
  priority: string;
  due_date: string | null;
  received_date: string | null;
  assigned_to: string | null;
  agency: string;
  region: string;
  ctd_section: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

export interface DbSafetyReport {
  id: string;
  case_number: string;
  product_id: string | null;
  event_type: string;
  event_description: string | null;
  seriousness: string;
  expectedness: string;
  causality: string | null;
  status: string;
  received_date: string;
  due_date: string | null;
  assigned_to: string | null;
  narrative: string | null;
  meddra_pt: string | null;
  meddra_llt: string | null;
  meddra_soc: string | null;
  ai_meddra_suggestions: unknown[] | null;
  ai_causality_assessment: string | null;
  ai_narrative_draft: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

export interface DbDocument {
  id: string;
  title: string;
  document_type: string;
  document_number: string | null;
  status: string;
  version: string;
  product_id: string | null;
  study_id: string | null;
  owner_id: string | null;
  ctd_section: string | null;
  content: string | null;
  summary: string | null;
  file_path: string | null;
  file_name: string | null;
  file_size: number | null;
  mime_type: string | null;
  checksum: string | null;
  effective_date: string | null;
  expiry_date: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

// =============================================================================
// AUTH TYPES
// =============================================================================

export interface SupabaseAuthUser {
  id: string;
  email: string;
  user_metadata: {
    name?: string;
    role?: UserRole;
    department?: string;
    title?: string;
    organization_id?: string;
  };
}

export interface SessionUser {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  department?: string;
  title?: string;
  organizationId?: string;
  isActive: boolean;
}
