/**
 * Sample CSR Data for Demo
 * 
 * Pre-loaded Clinical Study Report data for NEXAGEN (sorafenib analog)
 * Phase 3 study in Hepatocellular Carcinoma (HCC)
 * 
 * This data is structured to demonstrate RAG-powered authoring:
 * - Full sections with realistic regulatory content
 * - Tables with efficacy and safety data
 * - Statistical results with p-values and confidence intervals
 * 
 * @version 0.23.4
 */

// =============================================================================
// STUDY METADATA
// =============================================================================

export const DEMO_STUDY_METADATA = {
  productName: 'NEXAGEN',
  genericName: 'nexafenib',
  indication: 'Hepatocellular Carcinoma (HCC)',
  studyId: 'LIG-HCC-301',
  studyTitle: 'A Phase 3, Randomized, Double-Blind, Placebo-Controlled Study of NEXAGEN (Nexafenib) in Patients with Advanced Hepatocellular Carcinoma',
  sponsor: 'Ligature Therapeutics, Inc.',
  protocolVersion: '4.0',
  protocolDate: '2024-03-15',
  studyPhase: 'Phase 3',
  studyDesign: 'Randomized, double-blind, placebo-controlled',
  primaryEndpoint: 'Overall Survival (OS)',
  secondaryEndpoints: [
    'Progression-Free Survival (PFS)',
    'Objective Response Rate (ORR)',
    'Duration of Response (DOR)',
    'Time to Progression (TTP)',
    'Disease Control Rate (DCR)',
  ],
  enrollmentTarget: 750,
  enrollmentActual: 758,
  randomizationRatio: '2:1 (NEXAGEN:Placebo)',
  treatmentDuration: 'Until disease progression or unacceptable toxicity',
  regions: ['North America', 'Europe', 'Asia-Pacific'],
  sites: 127,
  countries: 24,
  firstPatientIn: '2023-06-12',
  lastPatientOut: '2025-09-28',
  databaseLock: '2025-10-15',
};

// =============================================================================
// SECTION 9 - STUDY DESIGN & METHODS
// =============================================================================

export const DEMO_SECTION_9_METHODS = `
9. STUDY DESIGN AND METHODS

9.1 Overall Study Design

This was a Phase 3, randomized, double-blind, placebo-controlled, multicenter study evaluating the efficacy and safety of NEXAGEN (nexafenib) in patients with advanced hepatocellular carcinoma (HCC). The study was conducted at 127 sites across 24 countries in North America, Europe, and Asia-Pacific regions.

Eligible patients were randomized in a 2:1 ratio to receive either NEXAGEN 400 mg twice daily or matching placebo. Randomization was stratified by:
- Geographic region (North America vs Europe vs Asia-Pacific)
- ECOG performance status (0 vs 1)
- Macrovascular invasion and/or extrahepatic spread (presence vs absence)
- Alpha-fetoprotein (AFP) level (<400 ng/mL vs ≥400 ng/mL)

Treatment continued until disease progression per RECIST v1.1, unacceptable toxicity, withdrawal of consent, or investigator decision. Patients who discontinued study treatment were followed for survival every 12 weeks.

9.2 Study Population

Key Inclusion Criteria:
- Histologically or cytologically confirmed HCC
- Barcelona Clinic Liver Cancer (BCLC) stage B or C
- Child-Pugh A liver function
- ECOG performance status 0 or 1
- At least one measurable lesion per RECIST v1.1
- Adequate hematologic, hepatic, and renal function
- No prior systemic therapy for advanced HCC

Key Exclusion Criteria:
- Prior treatment with sorafenib or other tyrosine kinase inhibitors
- Known fibrolamellar HCC, mixed hepatocholangiocarcinoma
- Active or history of hepatic encephalopathy
- Clinically significant ascites requiring intervention
- Active bleeding or high risk of bleeding
- Uncontrolled hypertension

9.3 Randomization and Blinding

Patients were randomized using an interactive web response system (IWRS). The randomization schedule was generated by an independent statistician using a permuted block design with varying block sizes. All patients, investigators, study personnel, and the sponsor were blinded to treatment assignment until database lock.

9.4 Study Assessments

Tumor assessments were performed by CT or MRI at baseline and every 8 weeks for the first 48 weeks, then every 12 weeks thereafter. All tumor assessments were reviewed by an independent central imaging review committee (IRC) who were blinded to treatment assignment.

Safety assessments included physical examinations, vital signs, ECOG performance status, clinical laboratory tests (hematology, chemistry, urinalysis), and adverse event monitoring at each visit.

9.5 Statistical Methods

The primary efficacy analysis was based on the intent-to-treat (ITT) population, defined as all randomized patients. The safety population included all patients who received at least one dose of study drug.

Overall survival was analyzed using a stratified log-rank test with stratification factors used at randomization. The hazard ratio and 95% confidence interval were estimated using a stratified Cox proportional hazards model. Kaplan-Meier methodology was used to estimate median OS and survival rates.

The study was designed with 90% power to detect a hazard ratio of 0.75 for OS (corresponding to an improvement in median OS from 10.7 months to 14.3 months) at a two-sided alpha level of 0.05. A total of 570 deaths were required for the final analysis.
`;

// =============================================================================
// SECTION 10 - PATIENT DISPOSITION & DEMOGRAPHICS
// =============================================================================

export const DEMO_SECTION_10_DEMOGRAPHICS = `
10. PATIENT DISPOSITION AND DEMOGRAPHICS

10.1 Patient Disposition

A total of 1,142 patients were screened, of whom 758 were randomized: 505 to the NEXAGEN arm and 253 to the placebo arm. The most common reasons for screen failure were not meeting liver function criteria (n=168), absence of measurable disease (n=89), and prior systemic therapy (n=67).

Of the randomized patients, 502 (99.4%) in the NEXAGEN arm and 251 (99.2%) in the placebo arm received at least one dose of study drug and were included in the safety population.

At the time of database lock (October 15, 2025), 187 patients (37.0%) in the NEXAGEN arm and 48 patients (19.0%) in the placebo arm remained on treatment. The primary reason for treatment discontinuation was disease progression (NEXAGEN: 234 [46.3%]; placebo: 168 [66.4%]).

Table 10.1 Patient Disposition
┌────────────────────────────────────┬─────────────────┬─────────────────┐
│ Parameter                          │ NEXAGEN (N=505) │ Placebo (N=253) │
├────────────────────────────────────┼─────────────────┼─────────────────┤
│ Received study treatment           │ 502 (99.4%)     │ 251 (99.2%)     │
│ Completed treatment                │ 42 (8.3%)       │ 12 (4.7%)       │
│ Ongoing treatment at data cutoff   │ 187 (37.0%)     │ 48 (19.0%)      │
│ Discontinued treatment             │ 273 (54.1%)     │ 191 (75.5%)     │
│   Disease progression              │ 234 (46.3%)     │ 168 (66.4%)     │
│   Adverse event                    │ 24 (4.8%)       │ 8 (3.2%)        │
│   Death                            │ 8 (1.6%)        │ 12 (4.7%)       │
│   Withdrawal by subject            │ 5 (1.0%)        │ 2 (0.8%)        │
│   Physician decision               │ 2 (0.4%)        │ 1 (0.4%)        │
└────────────────────────────────────┴─────────────────┴─────────────────┘

10.2 Demographics and Baseline Characteristics

Demographics and baseline characteristics were well balanced between treatment arms. The median age was 64 years (range: 24-88), with 81.4% male patients. The majority of patients were from Asia-Pacific (48.7%), followed by Europe (30.9%) and North America (20.4%).

Table 10.2 Demographics and Baseline Characteristics
┌────────────────────────────────────┬─────────────────┬─────────────────┐
│ Parameter                          │ NEXAGEN (N=505) │ Placebo (N=253) │
├────────────────────────────────────┼─────────────────┼─────────────────┤
│ Age (years)                        │                 │                 │
│   Median (range)                   │ 64 (26-88)      │ 63 (24-85)      │
│   ≥65 years                        │ 238 (47.1%)     │ 112 (44.3%)     │
│ Sex                                │                 │                 │
│   Male                             │ 412 (81.6%)     │ 205 (81.0%)     │
│   Female                           │ 93 (18.4%)      │ 48 (19.0%)      │
│ Race                               │                 │                 │
│   Asian                            │ 242 (47.9%)     │ 127 (50.2%)     │
│   White                            │ 222 (44.0%)     │ 104 (41.1%)     │
│   Black/African American           │ 28 (5.5%)       │ 16 (6.3%)       │
│   Other                            │ 13 (2.6%)       │ 6 (2.4%)        │
│ Geographic region                  │                 │                 │
│   Asia-Pacific                     │ 246 (48.7%)     │ 123 (48.6%)     │
│   Europe                           │ 156 (30.9%)     │ 78 (30.8%)      │
│   North America                    │ 103 (20.4%)     │ 52 (20.6%)      │
│ ECOG performance status            │                 │                 │
│   0                                │ 312 (61.8%)     │ 154 (60.9%)     │
│   1                                │ 193 (38.2%)     │ 99 (39.1%)      │
│ BCLC stage                         │                 │                 │
│   B                                │ 98 (19.4%)      │ 51 (20.2%)      │
│   C                                │ 407 (80.6%)     │ 202 (79.8%)     │
│ Child-Pugh class A                 │ 505 (100%)      │ 253 (100%)      │
│ Etiology of HCC                    │                 │                 │
│   Hepatitis B                      │ 198 (39.2%)     │ 102 (40.3%)     │
│   Hepatitis C                      │ 134 (26.5%)     │ 64 (25.3%)      │
│   Alcohol                          │ 89 (17.6%)      │ 47 (18.6%)      │
│   NASH/NAFLD                       │ 52 (10.3%)      │ 25 (9.9%)       │
│   Other/Unknown                    │ 32 (6.3%)       │ 15 (5.9%)       │
│ Macrovascular invasion             │ 178 (35.2%)     │ 91 (36.0%)      │
│ Extrahepatic spread                │ 287 (56.8%)     │ 142 (56.1%)     │
│ AFP ≥400 ng/mL                     │ 214 (42.4%)     │ 109 (43.1%)     │
└────────────────────────────────────┴─────────────────┴─────────────────┘
`;

// =============================================================================
// SECTION 11 - EFFICACY RESULTS
// =============================================================================

export const DEMO_SECTION_11_EFFICACY = `
11. EFFICACY RESULTS

11.1 Primary Endpoint: Overall Survival

At the time of the primary analysis (data cutoff: October 15, 2025), 412 deaths (54.4% of randomized patients) had occurred in the ITT population: 248 (49.1%) in the NEXAGEN arm and 164 (64.8%) in the placebo arm.

NEXAGEN demonstrated a statistically significant improvement in overall survival compared with placebo. The median OS was 14.8 months (95% CI: 13.4, 16.2) in the NEXAGEN arm versus 10.4 months (95% CI: 9.2, 11.6) in the placebo arm, corresponding to a hazard ratio of 0.69 (95% CI: 0.57, 0.84; stratified log-rank p<0.0001).

The 12-month survival rate was 61.2% (95% CI: 56.8%, 65.3%) in the NEXAGEN arm versus 44.7% (95% CI: 38.4%, 50.8%) in the placebo arm. The 18-month survival rate was 42.8% (95% CI: 38.2%, 47.3%) versus 26.9% (95% CI: 21.4%, 32.6%), respectively.

Table 11.1 Overall Survival Results (ITT Population)
┌────────────────────────────────────┬─────────────────┬─────────────────┐
│ Parameter                          │ NEXAGEN (N=505) │ Placebo (N=253) │
├────────────────────────────────────┼─────────────────┼─────────────────┤
│ Deaths, n (%)                      │ 248 (49.1%)     │ 164 (64.8%)     │
│ Median OS, months (95% CI)         │ 14.8 (13.4,16.2)│ 10.4 (9.2,11.6) │
│ Hazard ratio (95% CI)              │ 0.69 (0.57, 0.84)                 │
│ p-value (stratified log-rank)      │ <0.0001                           │
│ OS rate at 12 months (95% CI)      │ 61.2% (56.8,65.3)│ 44.7% (38.4,50.8)|
│ OS rate at 18 months (95% CI)      │ 42.8% (38.2,47.3)│ 26.9% (21.4,32.6)|
└────────────────────────────────────┴─────────────────┴─────────────────┘

11.2 Secondary Endpoints

11.2.1 Progression-Free Survival

Median PFS by investigator assessment was 6.8 months (95% CI: 5.9, 7.5) in the NEXAGEN arm versus 4.1 months (95% CI: 3.4, 4.8) in the placebo arm (HR=0.58; 95% CI: 0.49, 0.68; p<0.0001).

By independent central review, median PFS was 7.2 months (95% CI: 6.3, 8.0) versus 4.3 months (95% CI: 3.6, 5.0), respectively (HR=0.55; 95% CI: 0.47, 0.65; p<0.0001).

11.2.2 Objective Response Rate

The objective response rate by RECIST v1.1 (IRC assessment) was 24.6% (95% CI: 20.8%, 28.6%) in the NEXAGEN arm versus 5.1% (95% CI: 2.7%, 8.6%) in the placebo arm (p<0.0001).

Complete responses were observed in 8 patients (1.6%) in the NEXAGEN arm and 1 patient (0.4%) in the placebo arm. Partial responses were observed in 116 patients (23.0%) versus 12 patients (4.7%), respectively.

Table 11.2 Best Overall Response (IRC Assessment, ITT Population)
┌────────────────────────────────────┬─────────────────┬─────────────────┐
│ Best Overall Response              │ NEXAGEN (N=505) │ Placebo (N=253) │
├────────────────────────────────────┼─────────────────┼─────────────────┤
│ Complete response (CR)             │ 8 (1.6%)        │ 1 (0.4%)        │
│ Partial response (PR)              │ 116 (23.0%)     │ 12 (4.7%)       │
│ Stable disease (SD)                │ 267 (52.9%)     │ 124 (49.0%)     │
│ Progressive disease (PD)           │ 89 (17.6%)      │ 98 (38.7%)      │
│ Not evaluable                      │ 25 (5.0%)       │ 18 (7.1%)       │
│ Objective response rate (CR+PR)    │ 124 (24.6%)     │ 13 (5.1%)       │
│   95% CI                           │ (20.8%, 28.6%)  │ (2.7%, 8.6%)    │
│ Disease control rate (CR+PR+SD)    │ 391 (77.4%)     │ 137 (54.2%)     │
│   95% CI                           │ (73.5%, 81.0%)  │ (47.8%, 60.4%)  │
└────────────────────────────────────┴─────────────────┴─────────────────┘

11.2.3 Duration of Response

Among patients who achieved an objective response, the median duration of response was 11.2 months (95% CI: 9.4, 14.8) in the NEXAGEN arm versus 6.7 months (95% CI: 4.1, 9.8) in the placebo arm.

11.3 Subgroup Analyses

The treatment effect on overall survival was consistent across prespecified subgroups, including geographic region, ECOG performance status, macrovascular invasion status, extrahepatic spread, AFP level, etiology of HCC, and age groups. Hazard ratios for all subgroups favored NEXAGEN and ranged from 0.56 to 0.79.

Notable findings included:
- Asia-Pacific region: HR=0.65 (95% CI: 0.50, 0.85)
- Patients with AFP ≥400 ng/mL: HR=0.62 (95% CI: 0.47, 0.81)
- Patients with macrovascular invasion: HR=0.68 (95% CI: 0.51, 0.90)
`;

// =============================================================================
// SECTION 12 - SAFETY RESULTS
// =============================================================================

export const DEMO_SECTION_12_SAFETY = `
12. SAFETY RESULTS

12.1 Extent of Exposure

In the safety population, the median duration of treatment was 8.4 months (range: 0.1-26.8 months) in the NEXAGEN arm versus 4.2 months (range: 0.1-22.4 months) in the placebo arm. The median relative dose intensity was 92.3% in the NEXAGEN arm.

Dose reductions occurred in 184 patients (36.7%) in the NEXAGEN arm, most commonly due to hand-foot skin reaction (n=67), diarrhea (n=42), and hypertension (n=38). Dose interruptions occurred in 256 patients (51.0%) in the NEXAGEN arm.

12.2 Overview of Adverse Events

Treatment-emergent adverse events (TEAEs) were reported in 498 patients (99.2%) in the NEXAGEN arm and 234 patients (93.2%) in the placebo arm. Grade 3-4 TEAEs occurred in 312 patients (62.2%) versus 98 patients (39.0%), respectively.

Serious adverse events (SAEs) were reported in 178 patients (35.5%) in the NEXAGEN arm and 72 patients (28.7%) in the placebo arm. Treatment-related SAEs occurred in 89 patients (17.7%) versus 18 patients (7.2%), respectively.

Table 12.1 Overview of Adverse Events (Safety Population)
┌────────────────────────────────────┬─────────────────┬─────────────────┐
│ Category                           │ NEXAGEN (N=502) │ Placebo (N=251) │
├────────────────────────────────────┼─────────────────┼─────────────────┤
│ Any TEAE                           │ 498 (99.2%)     │ 234 (93.2%)     │
│ Grade 3-4 TEAE                     │ 312 (62.2%)     │ 98 (39.0%)      │
│ Treatment-related TEAE             │ 478 (95.2%)     │ 156 (62.2%)     │
│ Grade 3-4 treatment-related TEAE   │ 248 (49.4%)     │ 42 (16.7%)      │
│ Any SAE                            │ 178 (35.5%)     │ 72 (28.7%)      │
│ Treatment-related SAE              │ 89 (17.7%)      │ 18 (7.2%)       │
│ TEAE leading to dose reduction     │ 184 (36.7%)     │ 24 (9.6%)       │
│ TEAE leading to dose interruption  │ 256 (51.0%)     │ 48 (19.1%)      │
│ TEAE leading to discontinuation    │ 24 (4.8%)       │ 8 (3.2%)        │
│ Deaths                             │ 12 (2.4%)       │ 8 (3.2%)        │
│ Deaths due to TEAE                 │ 8 (1.6%)        │ 6 (2.4%)        │
│ Deaths due to treatment-related AE │ 2 (0.4%)        │ 0               │
└────────────────────────────────────┴─────────────────┴─────────────────┘

12.3 Common Adverse Events

The most common TEAEs (≥20% in either arm) in the NEXAGEN arm were diarrhea (68.5%), hand-foot skin reaction (58.2%), fatigue (52.4%), hypertension (48.6%), decreased appetite (42.8%), nausea (38.2%), and abdominal pain (32.5%).

Table 12.2 Treatment-Emergent Adverse Events (≥10% in Either Arm)
┌────────────────────────────────────┬─────────────────────────────────────────┐
│ Adverse Event                      │ NEXAGEN (N=502)       │ Placebo (N=251) │
│                                    │ All Grades  │ Grade ≥3│ All    │ Grade≥3│
├────────────────────────────────────┼─────────────┼─────────┼────────┼────────┤
│ Diarrhea                           │ 344 (68.5%) │ 48 (9.6%)│ 62 (24.7%)│ 4 (1.6%)|
│ Hand-foot skin reaction            │ 292 (58.2%) │ 84 (16.7%)│ 8 (3.2%)│ 0      |
│ Fatigue                            │ 263 (52.4%) │ 42 (8.4%)│ 78 (31.1%)│ 12 (4.8%)|
│ Hypertension                       │ 244 (48.6%) │ 72 (14.3%)│ 32 (12.7%)│ 8 (3.2%)|
│ Decreased appetite                 │ 215 (42.8%) │ 18 (3.6%)│ 68 (27.1%)│ 6 (2.4%)|
│ Nausea                             │ 192 (38.2%) │ 12 (2.4%)│ 52 (20.7%)│ 4 (1.6%)|
│ Abdominal pain                     │ 163 (32.5%) │ 24 (4.8%)│ 72 (28.7%)│ 18 (7.2%)|
│ Weight decreased                   │ 142 (28.3%) │ 8 (1.6%)│ 38 (15.1%)│ 2 (0.8%)|
│ Rash                               │ 138 (27.5%) │ 18 (3.6%)│ 24 (9.6%)│ 2 (0.8%)|
│ Alopecia                           │ 124 (24.7%) │ 0       │ 12 (4.8%)│ 0      |
│ Vomiting                           │ 118 (23.5%) │ 8 (1.6%)│ 34 (13.5%)│ 2 (0.8%)|
│ Constipation                       │ 98 (19.5%)  │ 4 (0.8%)│ 42 (16.7%)│ 2 (0.8%)|
│ AST increased                      │ 92 (18.3%)  │ 32 (6.4%)│ 36 (14.3%)│ 14 (5.6%)|
│ ALT increased                      │ 86 (17.1%)  │ 28 (5.6%)│ 32 (12.7%)│ 12 (4.8%)|
│ Bilirubin increased                │ 78 (15.5%)  │ 18 (3.6%)│ 28 (11.2%)│ 8 (3.2%)|
│ Proteinuria                        │ 68 (13.5%)  │ 8 (1.6%)│ 14 (5.6%)│ 2 (0.8%)|
│ Dysphonia                          │ 62 (12.4%)  │ 0       │ 8 (3.2%)│ 0      |
│ Headache                           │ 58 (11.6%)  │ 4 (0.8%)│ 24 (9.6%)│ 2 (0.8%)|
│ Epistaxis                          │ 52 (10.4%)  │ 2 (0.4%)│ 12 (4.8%)│ 0      |
└────────────────────────────────────┴─────────────┴─────────┴────────┴────────┘

12.4 Adverse Events of Special Interest

12.4.1 Hand-Foot Skin Reaction
Hand-foot skin reaction (HFSR) was the most common adverse event of special interest, occurring in 292 patients (58.2%) in the NEXAGEN arm versus 8 patients (3.2%) in the placebo arm. Grade 3 HFSR occurred in 84 patients (16.7%) in the NEXAGEN arm. The median time to first onset of HFSR was 15 days (range: 3-168 days). HFSR led to dose reduction in 67 patients (13.3%) and dose interruption in 89 patients (17.7%).

12.4.2 Hypertension
Treatment-emergent hypertension occurred in 244 patients (48.6%) in the NEXAGEN arm versus 32 patients (12.7%) in the placebo arm. Grade 3 hypertension occurred in 72 patients (14.3%) versus 8 patients (3.2%), respectively. Hypertension led to dose reduction in 38 patients (7.6%) and was managed with antihypertensive medications in most cases.

12.4.3 Hepatotoxicity
Hepatic adverse events including AST/ALT elevation, bilirubin increase, and hepatic failure were monitored closely. Grade 3-4 AST elevation occurred in 32 patients (6.4%) in the NEXAGEN arm versus 14 patients (5.6%) in the placebo arm. Two patients in the NEXAGEN arm had drug-induced liver injury that resolved with treatment discontinuation.

12.5 Deaths

During the study, 20 patients died due to adverse events: 12 (2.4%) in the NEXAGEN arm and 8 (3.2%) in the placebo arm. The most common cause of death was disease progression. Treatment-related deaths occurred in 2 patients (0.4%) in the NEXAGEN arm (1 hepatic failure, 1 hemorrhage).
`;

// =============================================================================
// SECTION 13 - PK RESULTS (abbreviated)
// =============================================================================

export const DEMO_SECTION_13_PK = `
13. PHARMACOKINETIC RESULTS

13.1 Pharmacokinetic Parameters

Population pharmacokinetic analysis was performed using plasma concentration data from 498 patients in the safety population who had evaluable PK samples.

NEXAGEN exhibited dose-proportional pharmacokinetics in the studied dose range. At the 400 mg twice daily dose, the geometric mean steady-state Cmax was 8.42 μg/mL (CV: 42%) and AUC0-12h was 67.8 μg·h/mL (CV: 38%). Time to peak concentration (Tmax) was approximately 3 hours (range: 1-6 hours).

The terminal half-life was approximately 28-32 hours, supporting twice-daily dosing. Steady state was achieved within 7-10 days of dosing initiation.

Table 13.1 Steady-State Pharmacokinetic Parameters (400 mg BID)
┌────────────────────────────────────┬─────────────────────────────────────┐
│ Parameter                          │ Geometric Mean (CV%)                │
├────────────────────────────────────┼─────────────────────────────────────┤
│ Cmax (μg/mL)                       │ 8.42 (42%)                          │
│ Cmin (μg/mL)                       │ 3.18 (48%)                          │
│ AUC0-12h (μg·h/mL)                 │ 67.8 (38%)                          │
│ Tmax (h)                           │ 3.0 (range: 1-6)                    │
│ t1/2 (h)                           │ 30.2 (28%)                          │
│ Accumulation ratio                 │ 2.8 (32%)                           │
└────────────────────────────────────┴─────────────────────────────────────┘

13.2 Exposure-Response Analysis

Exploratory exposure-response analyses suggested a positive relationship between NEXAGEN exposure (AUCss) and both efficacy (OS, PFS) and safety outcomes (HFSR, hypertension). Patients in the highest exposure quartile had numerically better OS (HR=0.58) compared to those in the lowest quartile (HR=0.78), although formal statistical comparisons were not performed.
`;

// =============================================================================
// SECTION 14 - DISCUSSION
// =============================================================================

export const DEMO_SECTION_14_DISCUSSION = `
14. DISCUSSION AND CONCLUSIONS

14.1 Summary of Efficacy

Study LIG-HCC-301 met its primary endpoint, demonstrating a statistically significant and clinically meaningful improvement in overall survival with NEXAGEN compared with placebo in patients with advanced HCC. The median OS was 14.8 months with NEXAGEN versus 10.4 months with placebo (HR=0.69; 95% CI: 0.57, 0.84; p<0.0001), representing a 31% reduction in the risk of death and a 4.4-month improvement in median survival.

The survival benefit was consistent across all prespecified subgroups, including patients with poor prognostic features such as macrovascular invasion, extrahepatic spread, and elevated AFP levels. This consistency supports the robustness of the primary finding.

Secondary efficacy endpoints further supported the clinical benefit of NEXAGEN:
- Significant improvement in PFS (median 6.8 vs 4.1 months; HR=0.58)
- Higher objective response rate (24.6% vs 5.1%; p<0.0001)
- Superior disease control rate (77.4% vs 54.2%)
- Longer duration of response (median 11.2 vs 6.7 months)

14.2 Safety Summary

The safety profile of NEXAGEN was consistent with its mechanism of action as a multikinase inhibitor and was generally manageable with dose modifications and supportive care. The most common adverse events were diarrhea, hand-foot skin reaction, fatigue, and hypertension.

Although Grade 3-4 adverse events were more common with NEXAGEN than placebo (62.2% vs 39.0%), the rate of treatment discontinuation due to adverse events was low (4.8%) and similar to placebo (3.2%). The rate of treatment-related deaths was 0.4% (2 patients), both of which were considered possibly related to study drug.

14.3 Benefit-Risk Assessment

The benefit-risk profile of NEXAGEN is favorable for patients with advanced HCC. The clinically meaningful improvement in overall survival outweighs the manageable increase in adverse events. The established dose modification guidelines and supportive care recommendations enable most patients to continue treatment while managing toxicities effectively.

14.4 Conclusions

NEXAGEN demonstrated superior efficacy compared with placebo in patients with advanced hepatocellular carcinoma, with a statistically significant and clinically meaningful improvement in overall survival. The safety profile was consistent with the known class effects of multikinase inhibitors and was generally manageable. These results support the use of NEXAGEN as a first-line treatment option for patients with advanced HCC.
`;

// =============================================================================
// COMBINED SECTIONS FOR RAG INGESTION
// =============================================================================

export const DEMO_CSR_FULL_TEXT = `
CLINICAL STUDY REPORT

Study LIG-HCC-301: A Phase 3, Randomized, Double-Blind, Placebo-Controlled Study of NEXAGEN (Nexafenib) in Patients with Advanced Hepatocellular Carcinoma

Sponsor: Ligature Therapeutics, Inc.
Protocol Version: 4.0
Database Lock: October 15, 2025

${DEMO_SECTION_9_METHODS}

${DEMO_SECTION_10_DEMOGRAPHICS}

${DEMO_SECTION_11_EFFICACY}

${DEMO_SECTION_12_SAFETY}

${DEMO_SECTION_13_PK}

${DEMO_SECTION_14_DISCUSSION}
`;

// =============================================================================
// EXPORT ALL SECTIONS
// =============================================================================

export const DEMO_CSR_SECTIONS = [
  { 
    number: '9', 
    title: 'Study Design and Methods', 
    content: DEMO_SECTION_9_METHODS,
    keywords: ['study design', 'randomization', 'blinding', 'statistical methods', 'RECIST', 'stratification']
  },
  { 
    number: '10', 
    title: 'Patient Disposition and Demographics', 
    content: DEMO_SECTION_10_DEMOGRAPHICS,
    keywords: ['demographics', 'baseline', 'disposition', 'enrollment', 'discontinuation', 'ECOG', 'Child-Pugh']
  },
  { 
    number: '11', 
    title: 'Efficacy Results', 
    content: DEMO_SECTION_11_EFFICACY,
    keywords: ['efficacy', 'overall survival', 'OS', 'PFS', 'hazard ratio', 'objective response', 'RECIST', 'p-value']
  },
  { 
    number: '12', 
    title: 'Safety Results', 
    content: DEMO_SECTION_12_SAFETY,
    keywords: ['safety', 'adverse events', 'AE', 'SAE', 'hand-foot', 'diarrhea', 'hypertension', 'deaths']
  },
  { 
    number: '13', 
    title: 'Pharmacokinetic Results', 
    content: DEMO_SECTION_13_PK,
    keywords: ['pharmacokinetics', 'PK', 'Cmax', 'AUC', 'half-life', 'exposure', 'steady-state']
  },
  { 
    number: '14', 
    title: 'Discussion and Conclusions', 
    content: DEMO_SECTION_14_DISCUSSION,
    keywords: ['discussion', 'conclusions', 'benefit-risk', 'summary', 'clinical significance']
  },
];

export default {
  DEMO_STUDY_METADATA,
  DEMO_CSR_SECTIONS,
  DEMO_CSR_FULL_TEXT,
};
